<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0501.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

fortune1000 = pd.read_csv("https://bcdanl.github.io/data/fortune1000_2025.csv")
fortune = fortune1000[[
    "Rank", "Company", "Sector", "Industry",
    "Revenues_M", "Profits_M", "Number_of_Employees"
]]

In [2]:
fortune["Sector_rev_mean"] = (
    fortune.groupby("Sector")["Revenues_M"].transform("mean")
)

/tmp/ipykernel_5061/474007793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fortune["Sector_rev_mean"] = (

In [3]:
fortune

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,Sector_rev_mean
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000,35478.235294
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000,35478.235294
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000,40791.927711
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000,24561.515152
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500,40791.927711
...,...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500,24561.515152
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720,23670.449438
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200,12881.538462
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760,23670.449438
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690,8686.949153

In [4]:
fortune["Rev_centered"] = (
    fortune
    .groupby("Sector")['Revenues_M']
    .transform(
        lambda x: x - x.mean()
    )
)

fortune

/tmp/ipykernel_5061/3605909550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fortune["Rev_centered"] = (

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,Sector_rev_mean,Rev_centered
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000,35478.235294,645511.764706
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000,35478.235294,602481.764706
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000,40791.927711,359488.072289
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000,24561.515152,366478.484848
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500,40791.927711,332018.072289
...,...,...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500,24561.515152,-21881.515152
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720,23670.449438,-20990.449438
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200,12881.538462,-10211.538462
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760,23670.449438,-21000.449438
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690,8686.949153,-6026.949153

In [6]:
def demean(s):
  return s - s.mean()

fortune["Rev_centered_def"] = (
    fortune
      .groupby("Sector")["Revenues_M"]
      .transform(demean)
)

fortune

/tmp/ipykernel_5061/340611788.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fortune["Rev_centered_def"] = (

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,Sector_rev_mean,Rev_centered,Rev_centered_def
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000,35478.235294,645511.764706,645511.764706
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000,35478.235294,602481.764706,602481.764706
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000,40791.927711,359488.072289,359488.072289
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000,24561.515152,366478.484848,366478.484848
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500,40791.927711,332018.072289,332018.072289
...,...,...,...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500,24561.515152,-21881.515152,-21881.515152
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720,23670.449438,-20990.449438,-20990.449438
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200,12881.538462,-10211.538462,-10211.538462
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760,23670.449438,-21000.449438,-21000.449438
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690,8686.949153,-6026.949153,-6026.949153

In [9]:
sectors = fortune.groupby("Sector")

fortune_sector = (
    fortune
    .assign(
        Year = 2025,
        nCompanies = sectors.transform('size'),
        Revenues_M_min = sectors['Revenues_M'].transform('min'),
        Profits_M_max = sectors['Profits_M'].transform('max'),
        Number_of_Employees_mean = sectors['Number_of_Employees'].transform('mean')
    )
)

fortune_sector

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,Sector_rev_mean,Rev_centered,Rev_centered_def,Year,nCompanies,Revenues_M_min,Profits_M_max,Number_of_Employees_mean
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000,35478.235294,645511.764706,645511.764706,2025,85,2720.0,62360.0,92020.235294
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000,35478.235294,602481.764706,602481.764706,2025,85,2720.0,62360.0,92020.235294
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000,40791.927711,359488.072289,359488.072289,2025,83,2700.0,17120.0,42671.566265
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000,24561.515152,366478.484848,366478.484848,2025,99,2680.0,100120.0,45229.090909
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500,40791.927711,332018.072289,332018.072289,2025,83,2700.0,17120.0,42671.566265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500,24561.515152,-21881.515152,-21881.515152,2025,99,2680.0,100120.0,45229.090909
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720,23670.449438,-20990.449438,-20990.449438,2025,178,2670.0,89000.0,22250.955056
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200,12881.538462,-10211.538462,-10211.538462,2025,26,2670.0,8710.0,22155.000000
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760,23670.449438,-21000.449438,-21000.449438,2025,178,2670.0,89000.0,22250.955056
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690,8686.949153,-6026.949153,-6026.949153,2025,59,2660.0,19740.0,29941.779661

In [10]:
f_2021_2025 = pd.read_csv(
    "https://bcdanl.github.io/data/fortune705_2021_2025.csv"
  )

f_2021_2025

,Year,Rank,Rank_mean,Company,Sector,Revenues_M,Profits_M,Number_of_employees
0,2025,1,1.0,Walmart,Retailing,680990.0,19440.0,2100000
1,2024,1,1.0,Walmart,Retailing,648125.0,15511.0,2100000
2,2023,1,1.0,Walmart,Retailing,611289.0,11680.0,2100000
3,2022,1,1.0,Walmart,Retailing,572754.0,13673.0,2300000
4,2021,1,1.0,Walmart,Retailing,523964.0,14881.0,2200000
...,...,...,...,...,...,...,...,...
3520,2023,955,971.4,SBA Communications,Financials,2634.0,461.0,1834
3521,2022,957,971.4,SBA Communications,Financials,2308.8,237.6,1596
3522,2021,994,971.4,SBA Communications,Financials,2014.6,147.0,1475
3523,2025,974,975.0,Vista Outdoor,Business Services,2750.0,-5.5,6400
3524,2021,976,975.0,Vista Outdoor,Business Services,2058.5,-648.4,5200

In [11]:
f_2021_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3525 entries, 0 to 3524
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Year                 3525 non-null   int64
 1   Rank                 3525 non-null   int64
 2   Rank_mean            3525 non-null   float64
 3   Company              3525 non-null   object
 4   Sector               3525 non-null   object
 5   Revenues_M           3525 non-null   float64
 6   Profits_M            3521 non-null   float64
 7   Number_of_employees  3525 non-null   int64
dtypes: float64(3), int64(3), object(2)
memory usage: 220.4+ KB

In [12]:
f_2021_2025['Revenues_M_last_year'] = (
  f_2021_2025
  .groupby('Company')['Revenues_M']
  .shift(-1)
)

f_2021_2025

,Year,Rank,Rank_mean,Company,Sector,Revenues_M,Profits_M,Number_of_employees,Revenues_M_last_year
0,2025,1,1.0,Walmart,Retailing,680990.0,19440.0,2100000,648125.0
1,2024,1,1.0,Walmart,Retailing,648125.0,15511.0,2100000,611289.0
2,2023,1,1.0,Walmart,Retailing,611289.0,11680.0,2100000,572754.0
3,2022,1,1.0,Walmart,Retailing,572754.0,13673.0,2300000,523964.0
4,2021,1,1.0,Walmart,Retailing,523964.0,14881.0,2200000,NaN
...,...,...,...,...,...,...,...,...,...
3520,2023,955,971.4,SBA Communications,Financials,2634.0,461.0,1834,2308.8
3521,2022,957,971.4,SBA Communications,Financials,2308.8,237.6,1596,2014.6
3522,2021,994,971.4,SBA Communications,Financials,2014.6,147.0,1475,NaN
3523,2025,974,975.0,Vista Outdoor,Business Services,2750.0,-5.5,6400,2058.5
3524,2021,976,975.0,Vista Outdoor,Business Services,2058.5,-648.4,5200,NaN

In [14]:
f_2021_2025['Revenue_Growth_Rate'] = (
    100 * ( f_2021_2025['Revenues_M'] - f_2021_2025['Revenues_M_last_year'] ) / f_2021_2025['Revenues_M_last_year']
)

f_2021_2025

,Year,Rank,Rank_mean,Company,Sector,Revenues_M,Profits_M,Number_of_employees,Revenues_M_last_year,Revenue_Growth_Rate
0,2025,1,1.0,Walmart,Retailing,680990.0,19440.0,2100000,648125.0,5.070781
1,2024,1,1.0,Walmart,Retailing,648125.0,15511.0,2100000,611289.0,6.025955
2,2023,1,1.0,Walmart,Retailing,611289.0,11680.0,2100000,572754.0,6.728019
3,2022,1,1.0,Walmart,Retailing,572754.0,13673.0,2300000,523964.0,9.311708
4,2021,1,1.0,Walmart,Retailing,523964.0,14881.0,2200000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3520,2023,955,971.4,SBA Communications,Financials,2634.0,461.0,1834,2308.8,14.085239
3521,2022,957,971.4,SBA Communications,Financials,2308.8,237.6,1596,2014.6,14.603395
3522,2021,994,971.4,SBA Communications,Financials,2014.6,147.0,1475,NaN,NaN
3523,2025,974,975.0,Vista Outdoor,Business Services,2750.0,-5.5,6400,2058.5,33.592422
3524,2021,976,975.0,Vista Outdoor,Business Services,2058.5,-648.4,5200,NaN,NaN

In [15]:
url_path = "https://bcdanl.github.io/data/fortune1000_2025_shuffled.csv"
fortune_shuffled = pd.read_csv(url_path)
sectors = fortune_shuffled.groupby("Sector")

fortune_shuffled

,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees
0,522,Arista Networks,ANET,Technology,Network and Other Communications Equipment,Santa Clara,California,7000.0,2850.0,$14.04B,$97.71B,4410
1,738,Upbound Group,UPBD,Retailing,Specialty Retailers: Other,Plano,Texas,4320.0,123.5,$2.65B,$1.38B,11970
2,741,Hyster-Yale,HY,Industrials,Industrial Machinery,Cleveland,Ohio,4310.0,142.3,$2.03B,$735.1M,8500
3,661,First Horizon,FHN,Financials,Commercial Banks,Memphis,Tennessee,5030.0,775.0,$82.15B,$9.98B,7200
4,412,Celanese,CE,Chemicals,Chemicals,Irving,Texas,10280.0,-1520.0,$22.86B,$6.34B,12160
...,...,...,...,...,...,...,...,...,...,...,...,...
995,107,Abbott Laboratories,ABT,Health Care,Medical Products and Equipment,Abbott Park,Illinois,41950.0,13400.0,$81.41B,$230.06B,114000
996,271,Universal Health Services,UHS,Health Care,Health Care: Medical Facilities,King of Prussia,Pennsylvania,15830.0,1140.0,$14.47B,$12.21B,87500
997,861,Extra Space Storage,EXR,Financials,Real estate,Salt Lake City,Utah,3380.0,854.7,$28.85B,$31.48B,8010
998,436,KeyCorp,KEY,Financials,Commercial Banks,Cleveland,Ohio,9240.0,-161.0,$187.17B,$17.52B,16750
999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000

In [16]:
sectors.nlargest(3, "Revenues_M")

AttributeError: 'DataFrameGroupBy' object has no attribute 'nlargest'

In [17]:
sectors.sort_values("Revenues_M", ascending = False)

AttributeError: 'DataFrameGroupBy' object has no attribute 'sort_values'

In [18]:
sectors.apply(lambda df: df.nlargest(1, "Revenues_M", keep="all"))

/tmp/ipykernel_5061/1196263043.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(lambda df: df.nlargest(1, "Revenues_M", keep="all"))

,,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees
Sector,,,,,,,,,,,,,
Aerospace & Defense,675,54,RTX,RTX,Aerospace & Defense,Aerospace & Defense,Arlington,Virginia,80740.0,4770.0,$162.86B,$176.85B,186000
Apparel,473,90,Nike,NKE,Apparel,Apparel,Beaverton,Oregon,51360.0,5700.0,$38.11B,$93.89B,79400
Business Services,549,127,Visa,V,Business Services,Financial Data Services,San Francisco,California,35930.0,19740.0,$94.51B,$685.9B,31600
Chemicals,999,103,Dow,DOW,Chemicals,Chemicals,Midland,Michigan,42960.0,1120.0,$57.31B,$24.65B,36000
Energy,298,8,Exxon Mobil,XOM,Energy,Petroleum Refining,Spring,Texas,349580.0,33680.0,$453.48B,$516.05B,60900
Engineering & Construction,726,123,D.R. Horton,DHI,Engineering & Construction,Homebuilders,Arlington,Texas,36800.0,4760.0,$36.1B,$40.06B,14770
Financials,259,6,Berkshire Hathaway,BRK.A,Financials,Insurance: Property and Casualty (Stock),Omaha,Nebraska,371430.0,89000.0,$1.15T,$1.15T,392400
Food & Drug Stores,138,26,Walgreens Boots Alliance,WBA,Food & Drug Stores,Food & Drug Stores,Deerfield,Illinois,147660.0,-8640.0,$81.04B,$9.66B,252500
"Food, Beverages & Tobacco",140,45,PepsiCo,PEP,"Food, Beverages & Tobacco",Food Consumer Products,Purchase,New York,91850.0,9580.0,$99.47B,$205.61B,319000
Health Care,225,3,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,Eden Prairie,Minnesota,400280.0,14400.0,$298.28B,$479.08B,400000
"Hotels, Restaurants & Leisure",343,126,Starbucks,SBUX,"Hotels, Restaurants & Leisure",Food Services,Seattle,Washington,36180.0,3760.0,$31.34B,$111.42B,361000
Household Products,573,51,Procter & Gamble,PG,Household Products,Household and Personal Products,Cincinnati,Ohio,84040.0,14880.0,$122.37B,$399.61B,108000
Industrials,98,64,Caterpillar,CAT,Industrials,Construction and Farm Machinery,Irving,Texas,64810.0,10790.0,$87.76B,$157.62B,112900
Materials,31,140,Nucor,NUE,Materials,Metals,Charlotte,North Carolina,30730.0,2030.0,$33.94B,$27.77B,32700
Media,619,46,Walt Disney,DIS,Media,Entertainment,Burbank,California,91360.0,4970.0,$196.22B,$178.43B,205040
Motor Vehicles & Parts,600,18,General Motors,GM,Motor Vehicles & Parts,Motor Vehicles & Parts,Detroit,Michigan,187440.0,6010.0,$279.76B,$46.79B,162000
Retailing,334,1,Walmart,WMT,Retailing,General Merchandisers,Bentonville,Arkansas,680990.0,19440.0,$260.82B,$703.8B,2100000
Technology,240,4,Apple,AAPL,Technology,"Computers, Office Equipment",Cupertino,California,391040.0,93740.0,$364.98B,$3.34T,164000
Telecommunications,200,30,Verizon Communications,VZ,Telecommunications,Telecommunications,New York,New York,134790.0,17510.0,$384.71B,$190.95B,99600
Transportation,558,47,UPS,UPS,Transportation,"Mail, Package, and Freight Delivery",Atlanta,Georgia,91070.0,5780.0,$70.07B,$93.22B,372180
Wholesalers,135,56,Sysco,SYY,Wholesalers,Wholesalers: Food and Grocery,Houston,Texas,78840.0,1960.0,$24.92B,$36.71B,76000

In [20]:
fortune_tops = sectors.apply(lambda df: df.nlargest(2, "Revenues_M", keep="all"))

/tmp/ipykernel_5061/1103772124.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fortune_tops = sectors.apply(lambda df: df.nlargest(2, "Revenues_M", keep="all"))

In [22]:
fortune_tops

                                   Rank                   Company Ticker  \
Sector
Aerospace & Defense           675    54                       RTX    RTX
                              959    59           Lockheed Martin    LMT
Apparel                       473    90                      Nike    NKE
                              341   405                        VF    VFC
Business Services             549   127                      Visa      V
                              9     137           PayPal Holdings   PYPL
Chemicals                     999   103                       Dow    DOW
                              373   174                        3M    MMM
Energy                        298     8               Exxon Mobil    XOM
                              513    16                   Chevron    CVX
Engineering & Construction    726   123               D.R. Horton    DHI
                              871   129                    Lennar    LEN
Financials                    259     6        Berkshire Hathaway  BRK.A
                              57     11            JPMorgan Chase    JPM
Food & Drug Stores            138    26  Walgreens Boots Alliance    WBA
                              636    27                    Kroger     KR
Food, Beverages & Tobacco     140    45                   PepsiCo    PEP
                              223    50    Archer Daniels Midland    ADM
Health Care                   225     3        UnitedHealth Group    UNH
                              834     5                CVS Health    CVS
Hotels, Restaurants & Leisure 343   126                 Starbucks   SBUX
                              364   165                McDonald's    MCD
Household Products            573    51          Procter & Gamble     PG
                              284   212         Colgate-Palmolive     CL
Industrials                   98     64               Caterpillar    CAT
                              97     89                     Deere     DE
Materials                     31    140                     Nucor    NUE
                              384   221          Cleveland-Cliffs    CLF
Media                         619    46               Walt Disney    DIS
                              461   114    Warner Bros. Discovery    WBD
Motor Vehicles & Parts        600    18            General Motors     GM
                              420    19                Ford Motor      F
Retailing                     334     1                   Walmart    WMT
                              915     2                    Amazon   AMZN
Technology                    240     4                     Apple   AAPL
                              374     7                  Alphabet  GOOGL
Telecommunications            200    30    Verizon Communications     VZ
                              921    35                   Comcast  CMCSA
Transportation                558    47                       UPS    UPS
                              626    49                     FedEx    FDX
Wholesalers                   135    56                     Sysco    SYY
                              139    73                 TD Synnex    SNX

                                                          Sector  \
Sector
Aerospace & Defense           675            Aerospace & Defense
                              959            Aerospace & Defense
Apparel                       473                        Apparel
                              341                        Apparel
Business Services             549              Business Services
                              9                Business Services
Chemicals                     999                      Chemicals
                              373                      Chemicals
Energy                        298                         Energy
                              513                         Energy
Engineering & Construction    726     Engineering & Construction
                              871     Engineering & Construction
Financials                    259                     Financials
                              57                      Financials
Food & Drug Stores            138             Food & Drug Stores
                              636             Food & Drug Stores
Food, Beverages & Tobacco     140      Food, Beverages & Tobacco
                              223      Food, Beverages & Tobacco
Health Care                   225                    Health Care
                              834                    Health Care
Hotels, Restaurants & Leisure 343  Hotels, Restaurants & Leisure
                              364  Hotels, Restaurants & Leisure
Household Products            573             Household Products
                              284             Household Products
Industrials                   98                     Industrials
                              97                     Industrials
Materials                     31                       Materials
                              384                      Materials
Media                         619                          Media
                              461                          Media
Motor Vehicles & Parts        600         Motor Vehicles & Parts
                              420         Motor Vehicles & Parts
Retailing                     334                      Retailing
                              915                      Retailing
Technology                    240                     Technology
                              374                     Technology
Telecommunications            200             Telecommunications
                              921             Telecommunications
Transportation                558                 Transportation
                              626                 Transportation
Wholesalers                   135                    Wholesalers
                              139                    Wholesalers

                                                                        Industry  \
Sector
Aerospace & Defense           675                            Aerospace & Defense
                              959                            Aerospace & Defense
Apparel                       473                                        Apparel
                              341                                        Apparel
Business Services             549                        Financial Data Services
                              9                          Financial Data Services
Chemicals                     999                                      Chemicals
                              373                                      Chemicals
Energy                        298                             Petroleum Refining
                              513                             Petroleum Refining
Engineering & Construction    726                                   Homebuilders
                              871                                   Homebuilders
Financials                    259       Insurance: Property and Casualty (Stock)
                              57                                Commercial Banks
Food & Drug Stores            138                             Food & Drug Stores
                              636                             Food & Drug Stores
Food, Beverages & Tobacco     140                         Food Consumer Products
                              223                                Food Production
Health Care                   225        Health Care: Insurance and Managed Care
                              834       Health Care: Pharmacy and Other Services
Hotels, Restaurants & Leisure 343                                  Food Services
                              364                                  Food Services
Household Products            573                Household and Personal Products
                              284                Household and Personal Products
Industrials                   98                 Construction and Farm Machinery
                              97                 Construction and Farm Machinery
Materials                     31                                          Metals
                              384                                         Metals
Media                         619                                  Entertainment
                              461                                  Entertainment
Motor Vehicles & Parts        600                         Motor Vehicles & Parts
                              420                         Motor Vehicles & Parts
Retailing                     334                          General Merchandisers
                              915                Internet Services and Retailing
Technology                    240                    Computers, Office Equipment
                              374                Internet Services and Retailing
Telecommunications            200                             Telecommunications
                              921                             Telecommunications
Transportation                558            Mail, Package, and Freight Delivery
                              626            Mail, Package, and Freight Delivery
Wholesalers                   135                  Wholesalers: Food and Grocery
                              139  Wholesalers: Electronics and Office Equipment

                                            City           State  Revenues_M  \
Sector
Aerospace & Defense           675      Arlington        Virginia     80740.0
                              959       Bethesda        Maryland     71040.0
Apparel                       473      Beaverton          Oregon     51360.0
                              341         Denver        Colorado     10450.0
Business Services             549  San Francisco      California     35930.0
                              9         San Jose      California     31800.0
Chemicals                     999        Midland        Michigan     42960.0
                              373       St. Paul       Minnesota     24570.0
Energy                        298         Spring           Texas    349580.0
                              513        Houston           Texas    202790.0
Engineering & Construction    726      Arlington           Texas     36800.0
                              871          Miami         Florida     35440.0
Financials                    259          Omaha        Nebraska    371430.0
                              57        New York        New York    278910.0
Food & Drug Stores            138      Deerfield        Illinois    147660.0
                              636     Cincinnati            Ohio    147120.0
Food, Beverages & Tobacco     140       Purchase        New York     91850.0
                              223        Chicago        Illinois     85530.0
Health Care                   225   Eden Prairie       Minnesota    400280.0
                              834     Woonsocket    Rhode Island    372810.0
Hotels, Restaurants & Leisure 343        Seattle      Washington     36180.0
                              364        Chicago        Illinois     25920.0
Household Products            573     Cincinnati            Ohio     84040.0
                              284       New York        New York     20100.0
Industrials                   98          Irving           Texas     64810.0
                              97          Moline        Illinois     51720.0
Materials                     31       Charlotte  North Carolina     30730.0
                              384      Cleveland            Ohio     19180.0
Media                         619        Burbank      California     91360.0
                              461       New York        New York     39320.0
Motor Vehicles & Parts        600        Detroit        Michigan    187440.0
                              420       Dearborn        Michigan    184990.0
Retailing                     334    Bentonville        Arkansas    680990.0
                              915        Seattle      Washington    637960.0
Technology                    240      Cupertino      California    391040.0
                              374  Mountain View      California    350020.0
Telecommunications            200       New York        New York    134790.0
                              921   Philadelphia    Pennsylvania    123730.0
Transportation                558        Atlanta         Georgia     91070.0
                              626        Memphis       Tennessee     87690.0
Wholesalers                   135        Houston           Texas     78840.0
                              139        Fremont      California     58450.0

                                   Profits_M    Assets Market_Value  \
Sector
Aerospace & Defense           675     4770.0  $162.86B     $176.85B
                              959     5340.0   $55.62B     $104.79B
Apparel                       473     5700.0   $38.11B      $93.89B
                              341     -968.9   $11.61B       $6.05B
Business Services             549    19740.0   $94.51B      $685.9B
                              9       4150.0   $81.61B      $64.55B
Chemicals                     999     1120.0   $57.31B      $24.65B
                              373     4170.0   $39.87B       $79.2B
Energy                        298    33680.0  $453.48B     $516.05B
                              513    17660.0  $256.94B     $292.71B
Engineering & Construction    726     4760.0    $36.1B      $40.06B
                              871     3930.0   $41.31B      $30.16B
Financials                    259    89000.0    $1.15T       $1.15T
                              57     58470.0       $4T     $685.88B
Food & Drug Stores            138    -8640.0   $81.04B       $9.66B
                              636     2670.0   $52.62B      $44.54B
Food, Beverages & Tobacco     140     9580.0   $99.47B     $205.61B
                              223     1800.0   $53.27B      $23.05B
Health Care                   225    14400.0  $298.28B     $479.08B
                              834     4610.0  $253.22B      $85.42B
Hotels, Restaurants & Leisure 343     3760.0   $31.34B     $111.42B
                              364     8220.0   $55.18B     $223.18B
Household Products            573    14880.0  $122.37B     $399.61B
                              284     2890.0   $16.05B         $76B
Industrials                   98     10790.0   $87.76B     $157.62B
                              97      7100.0  $107.32B     $127.39B
Materials                     31      2030.0   $33.94B      $27.77B
                              384     -754.0   $20.95B       $4.06B
Media                         619     4970.0  $196.22B     $178.43B
                              461   -11310.0  $104.56B      $26.34B
Motor Vehicles & Parts        600     6010.0  $279.76B      $46.79B
                              420     5880.0   $285.2B      $39.88B
Retailing                     334    19440.0  $260.82B      $703.8B
                              915    59250.0  $624.89B       $2.02T
Technology                    240    93740.0  $364.98B       $3.34T
                              374   100120.0  $450.26B       $1.89T
Telecommunications            200    17510.0  $384.71B     $190.95B
                              921    16190.0  $266.21B     $139.52B
Transportation                558     5780.0   $70.07B      $93.22B
                              626     4330.0   $87.01B      $58.41B
Wholesalers                   135     1960.0   $24.92B      $36.71B
                              139      689.1   $30.27B       $8.65B

                                   Number_of_Employees
Sector
Aerospace & Defense           675               186000
                              959               121000
Apparel                       473                79400
                              341                24000
Business Services             549                31600
                              9                  24400
Chemicals                     999                36000
                              373                61500
Energy                        298                60900
                              513                45300
Engineering & Construction    726                14770
                              871                13270
Financials                    259               392400
                              57                317230
Food & Drug Stores            138               252500
                              636               409000
Food, Beverages & Tobacco     140               319000
                              223                43210
Health Care                   225               400000
                              834               259500
Hotels, Restaurants & Leisure 343               361000
                              364               150000
Household Products            573               108000
                              284                34000
Industrials                   98                112900
                              97                 55520
Materials                     31                 32700
                              384                30000
Media                         619               205040
                              461                35000
Motor Vehicles & Parts        600               162000
                              420               171000
Retailing                     334              2100000
                              915              1560000
Technology                    240               164000
                              374               183320
Telecommunications            200                99600
                              921               182000
Transportation                558               372180
                              626               422100
Wholesalers                   135                76000
                              139                25750

In [21]:
fortune_tops.columns

Index(['Rank', 'Company', 'Ticker', 'Sector', 'Industry', 'City', 'State',
       'Revenues_M', 'Profits_M', 'Assets', 'Market_Value',
       'Number_of_Employees'],
      dtype='object')