<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0506.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classwork 17

In [1]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

cereal = pd.read_csv('https://bcdanl.github.io/data/cereals_oatmeal.csv')

In [2]:
cereal

                         Name    Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran         Nabisco  Cold        70   10.0       6
1           100% Natural Bran     Quaker Oats  Cold       120    2.0       8
2                    All-Bran       Kellogg's  Cold        70    9.0       5
3   All-Bran with Extra Fiber       Kellogg's  Cold        50   14.0       0
4              Almond Delight  Ralston Purina  Cold       110    1.0       8
..                        ...             ...   ...       ...    ...     ...
72                    Triples   General Mills  Cold       110    0.0       3
73                       Trix   General Mills  Cold       110    0.0      12
74                 Wheat Chex  Ralston Purina  Cold       100    3.0       3
75                   Wheaties   General Mills  Cold       100    3.0       3
76        Wheaties Honey Gold   General Mills  Cold       110    1.0       8

[77 rows x 6 columns]

In [3]:
cereal.columns

Index(['Name', 'Manufacturer', 'Type', 'Calories', 'Fiber', 'Sugars'], dtype='object')

## Q4

Add a Normalized_Sugars variable to the cereal DataFrame that standardizes each cereal’s sugar content within its manufacturer group.

In [ ]:
cereal['Normalized_Sugars'] = cereal.groupby('Manufacturer')['Sugars'].transform( lambda s: ( s - s.mean() ) / s.std()

In [8]:
q4 = (
    cereal
    .assign(
        Normalized_Sugars = cereal.groupby('Manufacturer')['Sugars'].transform(
            lambda s: ( s - s.mean() ) / s.std() ),
        Normalized_Sugars_ungrouped = ( cereal['Sugars'] - cereal['Sugars'].mean() ) / cereal['Sugars'].std()

    )
)
q4

,Name,Manufacturer,Type,Calories,Fiber,Sugars,Normalized_Sugars,Normalized_Sugars_ungrouped
0,100% Bran,Nabisco,Cold,70,10.0,6,1.458030,-0.207447
1,100% Natural Bran,Quaker Oats,Cold,120,2.0,8,0.540062,0.242508
2,All-Bran,Kellogg's,Cold,70,9.0,5,-0.569951,-0.432425
3,All-Bran with Extra Fiber,Kellogg's,Cold,50,14.0,0,-1.680872,-1.557313
4,Almond Delight,Ralston Purina,Cold,110,1.0,8,0.526212,0.242508
...,...,...,...,...,...,...,...,...
72,Triples,General Mills,Cold,110,0.0,3,-1.279350,-0.882380
73,Trix,General Mills,Cold,110,0.0,12,1.044607,1.142419
74,Wheat Chex,Ralston Purina,Cold,100,3.0,3,-0.877019,-0.882380
75,Wheaties,General Mills,Cold,100,3.0,3,-1.279350,-0.882380
76,Wheaties Honey Gold,General Mills,Cold,110,1.0,8,0.011737,0.242508

In [9]:
# q5

q5 = (
    cereal
    .groupby('Manufacturer')
    .apply(
        lambda df: df.nlargest(2, "Sugars", keep = "all")
    )
)

q5

/tmp/ipykernel_4135/1442716139.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

                                                             Name  \
Manufacturer
American Home Food Products 43                              Maypo
General Mills               70                  Total Raisin Bran
                            14                        Cocoa Puffs
                            18                      Count Chocula
Kellogg's                   66                             Smacks
                            6                         Apple Jacks
Nabisco                     0                           100% Bran
                            68            Strawberry Fruit Wheats
Post                        30                       Golden Crisp
                            52              Post Nat. Raisin Bran
Quaker Oats                 10                       Cap'n'Crunch
                            35                   Honey Graham Ohs
Ralston Purina              44   Muesli Raisins; Dates; & Almonds
                            45  Muesli Raisins; Peaches; & Pecans

                                               Manufacturer  Type  Calories  \
Manufacturer
American Home Food Products 43  American Home Food Products   Hot       100
General Mills               70                General Mills  Cold       140
                            14                General Mills  Cold       110
                            18                General Mills  Cold       110
Kellogg's                   66                    Kellogg's  Cold       110
                            6                     Kellogg's  Cold       110
Nabisco                     0                       Nabisco  Cold        70
                            68                      Nabisco  Cold        90
Post                        30                         Post  Cold       100
                            52                         Post  Cold       120
Quaker Oats                 10                  Quaker Oats  Cold       120
                            35                  Quaker Oats  Cold       120
Ralston Purina              44               Ralston Purina  Cold       150
                            45               Ralston Purina  Cold       150

                                Fiber  Sugars
Manufacturer
American Home Food Products 43    0.0       3
General Mills               70    4.0      14
                            14    0.0      13
                            18    0.0      13
Kellogg's                   66    1.0      15
                            6     1.0      14
Nabisco                     0    10.0       6
                            68    3.0       5
Post                        30    0.0      15
                            52    6.0      14
Quaker Oats                 10    0.0      12
                            35    1.0      11
Ralston Purina              44    3.0      11
                            45    3.0      11

## Q7

For each manufacturer, choose one “representative cereal” using these rules:

First, calculate the manufacturer’s average calories.

Keep only cereals with calories below the manufacturer’s average.

If a manufacturer has no cereals below its average calories, use all cereals from that manufacturer instead.

Among the remaining cereals, choose the cereal with the highest fiber.

If there is a tie in fiber, choose the cereal with the lowest sugars.

If there is still a tie, choose the cereal with the alphabetically first name.
Return the full row for the selected cereal.

In [11]:
def rep_cereal(df):
  avg = df['Calories'].mean()

  candidate =  df[ df['Calories'] < avg ]

  if len(candidate) == 0:
    candidate = df

  candidate = candidate.sort_values(['Fiber', 'Sugars', 'Name'],
                                    ascending = [False, True, True]).iloc[0]

  return candidate

q7 = (
    cereal
    .groupby('Manufacturer')
    .apply(rep_cereal)
)

q7

/tmp/ipykernel_4135/8887381.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(rep_cereal)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/google/colab/data_table.py", line 189, in _repr_javascript_module_
    return self._gen_js(self._preprocess_dataframe())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/google/colab/data_table.py", line 170, in _preprocess_dataframe
    dataframe = dataframe.reset_index()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/frame.py", line 6472, in reset_index
    new_obj.insert(
  File "/usr/local/lib/python3.12/dist-packages/pandas/core/frame.py", line 5158, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert Manufacturer, already exists

,Name,Manufacturer,Type,Calories,Fiber,Sugars
Manufacturer,,,,,,
American Home Food Products,Maypo,American Home Food Products,Hot,100,0.0,3
General Mills,Total Whole Grain,General Mills,Cold,100,3.0,3
Kellogg's,All-Bran with Extra Fiber,Kellogg's,Cold,50,14.0,0
Nabisco,100% Bran,Nabisco,Cold,70,10.0,6
Post,Bran Flakes,Post,Cold,90,5.0,5
Quaker Oats,Puffed Wheat,Quaker Oats,Cold,50,1.0,0
Ralston Purina,Bran Chex,Ralston Purina,Cold,90,4.0,6

In [12]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

fortune1000 = pd.read_csv("https://bcdanl.github.io/data/fortune1000_2025.csv")
fortune = fortune1000[[
    "Rank", "Company", "Sector", "Industry",
    "Revenues_M", "Profits_M", "Number_of_Employees"
]]

In [13]:
sector_and_industry = fortune.groupby(["Sector", "Industry"])

sector_and_industry.groups

{('Aerospace & Defense', 'Aerospace & Defense'): [53, 58, 62, 95, 109, 117, 202, 310, 367, 474, 497, 530, 558, 602, 641, 736, 794, 829, 868, 897, 985], ('Apparel', 'Apparel'): [89, 404, 440, 448, 533, 536, 555, 597, 681, 742, 764, 862, 888, 950], ('Business Services', 'Advertising, marketing'): [275, 396, 820, 951], ('Business Services', 'Diversified Outsourcing Services'): [219, 231, 238, 244, 426, 457, 540, 566, 591, 637, 659, 661, 678, 732, 765, 816, 858, 865, 933, 944, 955, 959, 965], ('Business Services', 'Education'): [688, 994, 999], ('Business Services', 'Equipment Leasing'): [980], ('Business Services', 'Financial Data Services'): [126, 136, 151, 178, 207, 304, 401, 412, 516, 549, 601, 673, 686, 738, 751, 755, 778, 780, 867, 940, 946], ('Business Services', 'Miscellaneous'): [754], ('Business Services', 'Specialty Retailers: Other'): [284], ('Business Services', 'Toys, Sporting Goods'): [973], ('Business Services', 'Waste Management'): [196, 265, 585, 646], ('Chemicals', 'Chemicals'): [102, 173, 190, 233, 273, 338, 344, 346, 368, 380, 411, 430, 503, 545, 576, 583, 593, 623, 745, 776, 838, 840, 876, 962], ('Energy', 'Energy'): [105, 129, 152, 185, 240, 638, 752, 991], ('Energy', 'Mining, Crude-Oil Production'): [74, 158, 168, 182, 224, 266, 326, 382, 421, 437, 502, 614, 640, 643, 662, 735, 749, 750, 844, 885, 907, 924, 931, 992], ('Energy', 'Oil and Gas Equipment, Services'): [154, 193, 442, 622, 739, 824, 968], ('Energy', 'Petroleum Refining'): [7, 15, 27, 28, 33, 134, 149, 335, 473, 753, 805], ('Energy', 'Pipelines'): [52, 77, 91, 199, 255, 274, 288, 403, 523, 669, 830, 920], ('Energy', 'Utilities: Gas and Electric'): [143, 160, 172, 175, 191, 217, 234, 263, 285, 318, 321, 325, 336, 342, 352, 354, 408, 449, 450, 453, 492, 504, 509, 588, 615, 652, 653, 683, 698, 760, 779, 823, 852, 914], ('Energy', 'Wholesalers: Diversified'): [895], ('Engineering & Construction', 'Engineering & Construction'): [183, 246, 256, 258, 299, 341, 519, 520, 554, 631, 645, 695, 734, 774, 864, 939, 949], ('Engineering & Construction', 'Homebuilders'): [122, 128, 228, 389, 395, 466, 525, 553, 713, 714, 719, 724, 910, 928], ('Financials', 'Commercial Banks'): [10, 16, 20, 31, 32, 39, 81, 104, 112, 130, 167, 197, 268, 292, 316, 319, 340, 350, 432, 435, 556, 656, 660, 664, 665, 712, 731, 756, 781, 835, 849, 853, 878, 901, 921, 925, 934, 948, 958, 964], ('Financials', 'Diversified Financials'): [24, 37, 41, 57, 174, 177, 184, 223, 229, 254, 320, 366, 402, 416, 468, 589, 599, 618, 722, 811, 818, 828, 893, 913, 942], ('Financials', 'Insurance: Life, Health (Mutual)'): [68, 97, 101, 108, 252, 298, 309, 387, 733], ('Financials', 'Insurance: Life, Health (stock)'): [59, 61, 135, 195, 221, 227, 262, 271, 329, 337, 463, 506, 511, 594, 607, 691, 720, 769, 870, 896], ('Financials', 'Insurance: Property and Casualty (Mutual)'): [35, 71, 269, 279, 322, 613, 674, 845, 882], ('Financials', 'Insurance: Property and Casualty (Stock)'): [5, 56, 65, 90, 92, 98, 156, 161, 201, 236, 250, 312, 315, 355, 370, 405, 459, 462, 561, 569, 612, 682, 685, 701], ('Financials', 'Real estate'): [127, 187, 383, 445, 464, 471, 543, 579, 598, 600, 608, 629, 639, 644, 677, 696, 708, 786, 796, 856, 860, 880, 902, 916, 932, 976, 989, 996, 998], ('Financials', 'Securities'): [144, 162, 163, 209, 259, 293, 339, 360, 431, 452, 501, 514, 544, 568, 581, 617, 647, 766, 846, 847, 911, 927], ('Food & Drug Stores', 'Food & Drug Stores'): [25, 26, 54, 70, 480, 603, 687, 728], ('Food, Beverages & Tobacco', 'Beverages'): [96, 283, 365, 417, 493, 527, 650, 758], ('Food, Beverages & Tobacco', 'Food Consumer Products'): [44, 124, 165, 215, 261, 331, 349, 351, 378, 424, 465, 476, 532, 550, 655, 866, 984], ('Food, Beverages & Tobacco', 'Food Production'): [49, 84, 114, 245, 377, 438, 498, 596], ('Food, Beverages & Tobacco', 'Tobacco'): [120, 208, 971], ('Health Care', 'Health Care: Insurance and Managed Care'): [2, 19, 22, 38, 110, 436, 986], ('Health Care', 'Health Care: Medical Facilities'): [60, 205, 270, 330, 334, 526, 578, 625, 744, 892, 894, 898], ('Health Care', 'Health Care: Pharmacy and Other Services'): [4, 12, 281, 327, 376, 418, 575, 663, 768, 915, 956, 961, 972], ('Health Care', 'Medical Products and Equipment'): [106, 179, 194, 210, 218, 247, 287, 458, 461, 482, 565, 697, 770, 771, 775, 787, 788, 804, 904, 936, 963, 967, 970], ('Health Care', 'Pharmaceuticals'): [47, 64, 66, 76, 93, 99, 133, 148, 297, 305, 384, 423, 434, 552, 721, 726, 746, 877, 941, 947, 960], ('Health Care', 'Wholesalers: Health Care'): [8, 9, 14, 332, 394, 542, 873], ('Hotels, Restaurants & Leisure', 'Food Services'): [125, 164, 369, 371, 372, 490, 624, 694, 716, 723, 837, 851], ('Hotels, Restaurants & Leisure', 'Hotels, Casinos, Resorts'): [170, 239, 373, 375, 379, 512, 535, 541, 666, 671, 689, 785, 793, 886, 938, 979], ('Household Products', 'Home Equipment, Furnishings'): [390, 477, 486, 676, 725, 826, 891], ('Household Products', 'Household and Personal Products'): [50, 211, 212, 278, 280, 515, 571, 573, 884, 922, 937], ('Household Products', 'Industrial Machinery'): [282], ('Household Products', 'Toys, Sporting Goods'): [621, 762, 988], ('Industrials', 'Construction and Farm Machinery'): [63, 88, 363, 392, 651, 705], ('Industrials', 'Electronics, Electrical Equip.'): [251, 323, 460, 470, 562, 577, 605, 667, 797, 800, 836, 883, 917], ('Industrials', 'Industrial Machinery'): [118, 131, 171, 214, 237, 267, 302, 407, 451, 455, 508, 628, 654, 707, 709, 740, 741, 761, 773, 790, 810, 825, 832, 871, 887, 974, 993], ('Materials', 'Building Materials, Glass'): [253, 386, 499, 529, 534, 546, 630, 635, 703, 806, 929, 935, 943, 990], ('Materials', 'Forest and Paper Products'): [510, 513, 808], ('Materials', 'Metals'): [139, 220, 235, 277, 308, 353, 475, 704, 729, 767, 854, 908, 966, 975], ('Materials', 'Motor Vehicles & Parts'): [815], ('Materials', 'Packaging, Containers'): [225, 343, 348, 358, 443, 444, 456, 537, 547, 587, 616, 620, 834], ('Media', 'Entertainment'): [45, 113, 115, 146, 189, 307, 447, 489, 494, 551, 619, 627, 658, 702, 747, 763, 795, 819, 822, 831, 841, 899, 903, 983], ('Media', 'Publishing, Printing'): [413, 997], ('Motor Vehicles & Parts', 'Motor Vehicles & Parts'): [17, 18, 42, 132, 188, 222, 306, 406, 409, 414, 570, 670, 792, 813, 850, 857, 879, 919, 981], ('Retailing', 'Automotive Retailing, Services'): [123, 140, 150, 159, 213, 241, 303, 313, 359, 439, 478, 574, 748], ('Retailing', 'General Merchandisers'): [0, 11, 40, 192, 206, 260, 290, 539, 679], ('Retailing', 'Internet Services and Retailing'): [1, 21, 141, 311, 356, 357, 381, 393, 410, 415, 604, 626, 649, 717, 802, 821, 827, 848, 861, 906, 954, 977, 978], ('Retailing', 'Specialty Retailers: Apparel'): [75, 203, 289, 398, 400, 472, 563, 609, 632, 675, 909, 912, 982], ('Retailing', 'Specialty Retailers: Other'): [23, 51, 107, 111, 138, 226, 230, 248, 295, 296, 317, 374, 388, 481, 487, 505, 522, 572, 584, 718, 737, 789, 798, 814, 839, 859, 889], ('Technology', 'Computer Software'): [13, 86, 119, 200, 257, 385, 454, 518, 538, 567, 580, 586, 692, 699, 700, 730, 783, 801, 869, 918, 945, 969, 995], ('Technology', 'Computers, Office Equipment'): [3, 43, 83, 142, 291, 328, 559, 564, 812, 890], ('Technology', 'Electronics, Electrical Equip.'): [817], ('Technology', 'Information Technology Services'): [67, 204, 216, 249, 264, 314, 397, 425, 446, 479, 483, 495, 560, 634, 690], ('Technology', 'Internet Services and Retailing'): [6, 100, 181, 592, 706, 777], ('Technology', 'Network and Other Communications Equipment'): [82, 286, 391, 469, 521, 610, 657, 743, 772, 953], ('Technology', 'Scientific,Photographic and  Control Equipment'): [103, 524, 528, 548, 668, 727, 791, 863, 923], ('Technology', 'Semiconductors and Other Electronic Components'): [30, 85, 87, 116, 147, 157, 166, 169, 276, 294, 419, 429, 484, 488, 517, 557, 595, 693, 759, 782, 809, 833, 875, 930, 952], ('Telecommunications', 'Telecommunications'): [29, 34, 36, 78, 272, 324, 441, 582, 672], ('Transportation', 'Airlines'): [69, 73, 80, 155, 361, 433, 680, 807, 843], ('Transportation', 'Mail, Package, and Freight Delivery'): [46, 48], ('Transportation', 'Railroads'): [176, 300, 345], ('Transportation', 'Shipping'): [855, 872], ('Transportation', 'Transportation Equipment'): [507, 642, 648, 842, 900], ('Transportation', 'Transportation and Logistics'): [232, 333, 362, 399, 467, 636, 784], ('Transportation', 'Trucking, Truck Leasing'): [347, 500, 590, 606, 684, 710, 757, 881, 905], ('Wholesalers', 'Energy'): [243], ('Wholesalers', 'Information Technology Services'): [957], ('Wholesalers', 'Wholesalers: Diversified'): [145, 186, 198, 242, 301, 364, 420, 422, 428, 485, 491, 496, 531, 611, 633, 711, 715, 799, 926, 987], ('Wholesalers', 'Wholesalers: Electronics and Office Equipment'): [72, 94, 153, 180, 874], ('Wholesalers', 'Wholesalers: Food and Grocery'): [55, 79, 121, 137, 427, 803]}

In [14]:

len(sector_and_industry)

83

In [15]:

sector_and_industry.describe()

                                                                   Rank  \
                                                                  count
Sector              Industry
Aerospace & Defense Aerospace & Defense                            21.0
Apparel             Apparel                                        14.0
Business Services   Advertising, marketing                          4.0
                    Diversified Outsourcing Services               23.0
                    Education                                       3.0
...                                                                 ...
Wholesalers         Energy                                          1.0
                    Information Technology Services                 1.0
                    Wholesalers: Diversified                       20.0
                    Wholesalers: Electronics and Office Equipment   5.0
                    Wholesalers: Food and Grocery                   6.0

                                                                               \
                                                                         mean
Sector              Industry
Aerospace & Defense Aerospace & Defense                            466.904762
Apparel             Apparel                                        607.357143
Business Services   Advertising, marketing                         611.500000
                    Diversified Outsourcing Services               650.521739
                    Education                                      894.666667
...                                                                       ...
Wholesalers         Energy                                         244.000000
                    Information Technology Services                958.000000
                    Wholesalers: Diversified                       505.550000
                    Wholesalers: Electronics and Office Equipment  275.600000
                    Wholesalers: Food and Grocery                  271.333333

                                                                               \
                                                                          std
Sector              Industry
Aerospace & Defense Aerospace & Defense                            314.853760
Apparel             Apparel                                        229.716081
Business Services   Advertising, marketing                         325.781624
                    Diversified Outsourcing Services               252.115030
                    Education                                      178.130102
...                                                                       ...
Wholesalers         Energy                                                NaN
                    Information Technology Services                       NaN
                    Wholesalers: Diversified                       239.277965
                    Wholesalers: Electronics and Office Equipment  337.890219
                    Wholesalers: Food and Grocery                  293.711877

                                                                          \
                                                                     min
Sector              Industry
Aerospace & Defense Aerospace & Defense                             54.0
Apparel             Apparel                                         90.0
Business Services   Advertising, marketing                         276.0
                    Diversified Outsourcing Services               220.0
                    Education                                      689.0
...                                                                  ...
Wholesalers         Energy                                         244.0
                    Information Technology Services                958.0
                    Wholesalers: Diversified                       146.0
                    Wholesalers: Electronics and Office Equipment   73.0
                    Wholesalers: Food and Grocery                   56.0

                                                                           \
                                                                      25%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            118.00
Apparel             Apparel                                        470.25
Business Services   Advertising, marketing                         366.75
                    Diversified Outsourcing Services               499.50
                    Education                                      842.00
...                                                                   ...
Wholesalers         Energy                                         244.00
                    Information Technology Services                958.00
                    Wholesalers: Diversified                       349.25
                    Wholesalers: Electronics and Office Equipment   95.00
                    Wholesalers: Food and Grocery                   90.50

                                                                          \
                                                                     50%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            498.0
Apparel             Apparel                                        577.0
Business Services   Advertising, marketing                         609.0
                    Diversified Outsourcing Services               662.0
                    Education                                      995.0
...                                                                  ...
Wholesalers         Energy                                         244.0
                    Information Technology Services                958.0
                    Wholesalers: Diversified                       489.0
                    Wholesalers: Electronics and Office Equipment  154.0
                    Wholesalers: Food and Grocery                  130.0

                                                                           \
                                                                      75%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            737.00
Apparel             Apparel                                        759.50
Business Services   Advertising, marketing                         853.75
                    Diversified Outsourcing Services               862.50
                    Education                                      997.50
...                                                                   ...
Wholesalers         Energy                                         244.00
                    Information Technology Services                958.00
                    Wholesalers: Diversified                       653.50
                    Wholesalers: Electronics and Office Equipment  181.00
                    Wholesalers: Food and Grocery                  355.50

                                                                           \
                                                                      max
Sector              Industry
Aerospace & Defense Aerospace & Defense                             986.0
Apparel             Apparel                                         951.0
Business Services   Advertising, marketing                          952.0
                    Diversified Outsourcing Services                966.0
                    Education                                      1000.0
...                                                                   ...
Wholesalers         Energy                                          244.0
                    Information Technology Services                 958.0
                    Wholesalers: Diversified                        988.0
                    Wholesalers: Electronics and Office Equipment   875.0
                    Wholesalers: Food and Grocery                   804.0

                                                                  Revenues_M  \
                                                                       count
Sector              Industry
Aerospace & Defense Aerospace & Defense                                 21.0
Apparel             Apparel                                             14.0
Business Services   Advertising, marketing                               4.0
                    Diversified Outsourcing Services                    23.0
                    Education                                            3.0
...                                                                      ...
Wholesalers         Energy                                               1.0
                    Information Technology Services                      1.0
                    Wholesalers: Diversified                            20.0
                    Wholesalers: Electronics and Office Equipment        5.0
                    Wholesalers: Food and Grocery                        6.0

                                                                                 \
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace & Defense                            21551.904762
Apparel             Apparel                                         9105.714286
Business Services   Advertising, marketing                          8217.500000
                    Diversified Outsourcing Services                7009.130435
                    Education                                       3380.000000
...                                                                         ...
Wholesalers         Energy                                         17160.000000
                    Information Technology Services                 2800.000000
                    Wholesalers: Diversified                       10285.500000
                    Wholesalers: Electronics and Office Equipment  32274.000000
                    Wholesalers: Food and Grocery                  35953.333333

                                                                   ...  \
                                                                   ...
Sector              Industry                                       ...
Aerospace & Defense Aerospace & Defense                            ...
Apparel             Apparel                                        ...
Business Services   Advertising, marketing                         ...
                    Diversified Outsourcing Services               ...
                    Education                                      ...
...                                                                ...
Wholesalers         Energy                                         ...
                    Information Technology Services                ...
                    Wholesalers: Diversified                       ...
                    Wholesalers: Electronics and Office Equipment  ...
                    Wholesalers: Food and Grocery                  ...

                                                                  Profits_M  \
                                                                        75%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            1710.000
Apparel             Apparel                                         731.275
Business Services   Advertising, marketing                          887.125
                    Diversified Outsourcing Services                446.200
                    Education                                       432.400
...                                                                     ...
Wholesalers         Energy                                          110.300
                    Information Technology Services                  87.100
                    Wholesalers: Diversified                        696.900
                    Wholesalers: Electronics and Office Equipment   498.700
                    Wholesalers: Food and Grocery                   479.475

                                                                           \
                                                                      max
Sector              Industry
Aerospace & Defense Aerospace & Defense                            6560.0
Apparel             Apparel                                        5700.0
Business Services   Advertising, marketing                         1480.0
                    Diversified Outsourcing Services               3750.0
                    Education                                       724.6
...                                                                   ...
Wholesalers         Energy                                          110.3
                    Information Technology Services                  87.1
                    Wholesalers: Diversified                       1910.0
                    Wholesalers: Electronics and Office Equipment   689.1
                    Wholesalers: Food and Grocery                  1960.0

                                                                  Number_of_Employees  \
                                                                                count
Sector              Industry
Aerospace & Defense Aerospace & Defense                                          21.0
Apparel             Apparel                                                      14.0
Business Services   Advertising, marketing                                        4.0
                    Diversified Outsourcing Services                             23.0
                    Education                                                     3.0
...                                                                               ...
Wholesalers         Energy                                                        1.0
                    Information Technology Services                               1.0
                    Wholesalers: Diversified                                     20.0
                    Wholesalers: Electronics and Office Equipment                 5.0
                    Wholesalers: Food and Grocery                                 6.0

                                                                                 \
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace & Defense                            49547.619048
Apparel             Apparel                                        20442.857143
Business Services   Advertising, marketing                         46107.500000
                    Diversified Outsourcing Services               38674.782609
                    Education                                      31093.333333
...                                                                         ...
Wholesalers         Energy                                          3830.000000
                    Information Technology Services                 2580.000000
                    Wholesalers: Diversified                       15180.800000
                    Wholesalers: Electronics and Office Equipment  18232.000000
                    Wholesalers: Food and Grocery                  31861.666667

                                                                                 \
                                                                            std
Sector              Industry
Aerospace & Defense Aerospace & Defense                            55310.208904
Apparel             Apparel                                        19245.402819
Business Services   Advertising, marketing                         25634.135282
                    Diversified Outsourcing Services               56540.996138
                    Education                                      13101.222589
...                                                                         ...
Wholesalers         Energy                                                  NaN
                    Information Technology Services                         NaN
                    Wholesalers: Diversified                       16213.015764
                    Wholesalers: Electronics and Office Equipment   9889.669863
                    Wholesalers: Food and Grocery                  24465.776437

                                                                            \
                                                                       min
Sector              Industry
Aerospace & Defense Aerospace & Defense                             7700.0
Apparel             Apparel                                         4050.0
Business Services   Advertising, marketing                         13230.0
                    Diversified Outsourcing Services                3600.0
                    Education                                      17540.0
...                                                                    ...
Wholesalers         Energy                                          3830.0
                    Information Technology Services                 2580.0
                    Wholesalers: Diversified                         486.0
                    Wholesalers: Electronics and Office Equipment   2300.0
                    Wholesalers: Food and Grocery                   5030.0

                                                                            \
                                                                       25%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            13500.0
Apparel             Apparel                                        10060.0
Business Services   Advertising, marketing                         35557.5
                    Diversified Outsourcing Services               11150.0
                    Education                                      24795.0
...                                                                    ...
Wholesalers         Energy                                          3830.0
                    Information Technology Services                 2580.0
                    Wholesalers: Diversified                        6400.0
                    Wholesalers: Electronics and Office Equipment  15460.0
                    Wholesalers: Food and Grocery                  18332.5

                                                                            \
                                                                       50%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            20370.0
Apparel             Apparel                                        15450.0
Business Services   Advertising, marketing                         48150.0
                    Diversified Outsourcing Services               19350.0
                    Education                                      32050.0
...                                                                    ...
Wholesalers         Energy                                          3830.0
                    Information Technology Services                 2580.0
                    Wholesalers: Diversified                        7845.0
                    Wholesalers: Electronics and Office Equipment  21520.0
                    Wholesalers: Food and Grocery                  29165.0

                                                                            \
                                                                       75%
Sector              Industry
Aerospace & Defense Aerospace & Defense                            53000.0
Apparel             Apparel                                        21275.0
Business Services   Advertising, marketing                         58700.0
                    Diversified Outsourcing Services               45275.0

In [16]:
agg_tbl = (
    fortune
    .groupby(["Sector", "Industry"])
    .agg(
        n_companies = ("Company",   "size"),
        avg_rev     = ("Revenues_M","mean"),
        tot_rev     = ("Revenues_M","sum")
    )
    .reset_index()  # Flattens the MultiIndex into ordinary columns
)

agg_tbl

,Sector,Industry,n_companies,avg_rev,tot_rev
0,Aerospace & Defense,Aerospace & Defense,21,21551.904762,452590.0
1,Apparel,Apparel,14,9105.714286,127480.0
2,Business Services,"Advertising, marketing",4,8217.500000,32870.0
3,Business Services,Diversified Outsourcing Services,23,7009.130435,161210.0
4,Business Services,Education,3,3380.000000,10140.0
...,...,...,...,...,...
78,Wholesalers,Energy,1,17160.000000,17160.0
79,Wholesalers,Information Technology Services,1,2800.000000,2800.0
80,Wholesalers,Wholesalers: Diversified,20,10285.500000,205710.0
81,Wholesalers,Wholesalers: Electronics and Office Equipment,5,32274.000000,161370.0
82,Wholesalers,Wholesalers: Food and Grocery,6,35953.333333,215720.0

In [17]:
fortune['pct_of_industry_rev'] = (
        fortune
        .groupby(["Sector", "Industry"])["Revenues_M"]
        .transform(lambda x: x / x.sum() * 100)
)

fortune

/tmp/ipykernel_4135/3823158045.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fortune['pct_of_industry_rev'] = (

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,pct_of_industry_rev
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000,60.357542
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000,66.306359
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000,43.955416
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000,63.305812
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500,53.571583
...,...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500,0.575700
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720,1.394816
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200,20.924765
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760,1.389612
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690,26.232742

In [18]:
def above_median(df):
    med = df["Revenues_M"].median()
    return df[ df["Revenues_M"] > med ]

(
    fortune
    .groupby(["Sector", "Industry"])
    .apply(above_median)
)

/tmp/ipykernel_4135/3816298926.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(above_median)

                                                                       Rank  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53     54
                                                                  58     59
                                                                  62     63
                                                                  95     96
                                                                  109   110
...                                                                     ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72     73
                                                                  94     95
                    Wholesalers: Food and Grocery                 55     56
                                                                  79     80
                                                                  121   122

                                                                                      Company  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53                      RTX
                                                                  58          Lockheed Martin
                                                                  62                   Boeing
                                                                  95         General Dynamics
                                                                  109        Northrop Grumman
...                                                                                       ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72                TD Synnex
                                                                  94     Ingram Micro Holding
                    Wholesalers: Food and Grocery                 55                    Sysco
                                                                  79   Performance Food Group
                                                                  121        US Foods Holding

                                                                                    Sector  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53   Aerospace & Defense
                                                                  58   Aerospace & Defense
                                                                  62   Aerospace & Defense
                                                                  95   Aerospace & Defense
                                                                  109  Aerospace & Defense
...                                                                                    ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72           Wholesalers
                                                                  94           Wholesalers
                    Wholesalers: Food and Grocery                 55           Wholesalers
                                                                  79           Wholesalers
                                                                  121          Wholesalers

                                                                                                            Industry  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53                             Aerospace & Defense
                                                                  58                             Aerospace & Defense
                                                                  62                             Aerospace & Defense
                                                                  95                             Aerospace & Defense
                                                                  109                            Aerospace & Defense
...                                                                                                              ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72   Wholesalers: Electronics and Office Equipment
                                                                  94   Wholesalers: Electronics and Office Equipment
                    Wholesalers: Food and Grocery                 55                   Wholesalers: Food and Grocery
                                                                  79                   Wholesalers: Food and Grocery
                                                                  121                  Wholesalers: Food and Grocery

                                                                       Revenues_M  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53      80740.0
                                                                  58      71040.0
                                                                  62      66520.0
                                                                  95      47720.0
                                                                  109     41030.0
...                                                                           ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72      58450.0
                                                                  94      47980.0
                    Wholesalers: Food and Grocery                 55      78840.0
                                                                  79      54680.0
                                                                  121     37880.0

                                                                       Profits_M  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53      4770.0
                                                                  58      5340.0
                                                                  62    -11820.0
                                                                  95      3780.0
                                                                  109     4170.0
...                                                                          ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72       689.1
                                                                  94       264.2
                    Wholesalers: Food and Grocery                 55      1960.0
                                                                  79       435.9
                                                                  121      494.0

                                                                       Number_of_Employees  \
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53                186000
                                                                  58                121000
                                                                  62                172000
                                                                  95                117000
                                                                  109                97000
...                                                                                    ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72                 25750
                                                                  94                 26130
                    Wholesalers: Food and Grocery                 55                 76000
                                                                  79                 36810
                                                                  121                30000

                                                                       pct_of_industry_rev
Sector              Industry
Aerospace & Defense Aerospace & Defense                           53             17.839546
                                                                  58             15.696326
                                                                  62             14.697629
                                                                  95             10.543759
                                                                  109             9.065600
...                                                                                    ...
Wholesalers         Wholesalers: Electronics and Office Equipment 72             36.221107
                                                                  94             29.732912
                    Wholesalers: Food and Grocery                 55             36.547376
                                                                  79             25.347673
                                                                  121            17.559800

[474 rows x 8 columns]