<a href="https://colab.research.google.com/github/bcdanl/210-code/blob/main/danl_210_class_2026_0429.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Below is for an interactive display of DataFrame in Colab
from google.colab import data_table
data_table.enable_dataframe_formatter()

fortune1000 = pd.read_csv("https://bcdanl.github.io/data/fortune1000_2025.csv")
fortune1000

,Rank,Company,Ticker,Sector,Industry,City,State,Revenues_M,Profits_M,Assets,Market_Value,Number_of_Employees
0,1,Walmart,WMT,Retailing,General Merchandisers,Bentonville,Arkansas,680990.0,19440.0,$260.82B,$703.8B,2100000
1,2,Amazon,AMZN,Retailing,Internet Services and Retailing,Seattle,Washington,637960.0,59250.0,$624.89B,$2.02T,1560000
2,3,UnitedHealth Group,UNH,Health Care,Health Care: Insurance and Managed Care,Eden Prairie,Minnesota,400280.0,14400.0,$298.28B,$479.08B,400000
3,4,Apple,AAPL,Technology,"Computers, Office Equipment",Cupertino,California,391040.0,93740.0,$364.98B,$3.34T,164000
4,5,CVS Health,CVS,Health Care,Health Care: Pharmacy and Other Services,Woonsocket,Rhode Island,372810.0,4610.0,$253.22B,$85.42B,259500
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Datadog,DDOG,Technology,Computer Software,New York,New York,2680.0,183.7,$5.79B,$34.01B,6500
996,997,SBA Communications,SBAC,Financials,Real estate,Boca Raton,Florida,2680.0,749.5,$11.42B,$23.68B,1720
997,998,Quad/Graphics,QUAD,Media,"Publishing, Printing",Sussex,Wisconsin,2670.0,-50.9,$1.3B,$285.3M,12200
998,999,Americold Realty Trust,COLD,Financials,Real estate,Atlanta,Georgia,2670.0,-94.3,$7.74B,$6.1B,13760
999,1000,KinderCare Learning,KLC,Business Services,Education,Lake Oswego,Oregon,2660.0,-92.8,$3.65B,$1.37B,43690

In [3]:
fortune = fortune1000[[
    "Rank", "Company", "Sector", "Industry",
    "Revenues_M", "Profits_M", "Number_of_Employees"
]]

fortune

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500
...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690

In [28]:
fortune.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 1000 non-null   int64
 1   Company              1000 non-null   object
 2   Sector               1000 non-null   object
 3   Industry             1000 non-null   object
 4   Revenues_M           1000 non-null   float64
 5   Profits_M            999 non-null    float64
 6   Number_of_Employees  1000 non-null   int64
dtypes: float64(2), int64(2), object(3)
memory usage: 54.8+ KB

In [4]:
fortune["Sector"].unique()

array(['Retailing', 'Health Care', 'Technology', 'Financials', 'Energy',
       'Motor Vehicles & Parts', 'Food & Drug Stores',
       'Telecommunications', 'Food, Beverages & Tobacco', 'Media',
       'Transportation', 'Household Products', 'Aerospace & Defense',
       'Wholesalers', 'Industrials', 'Apparel', 'Chemicals',
       'Engineering & Construction', 'Hotels, Restaurants & Leisure',
       'Business Services', 'Materials'], dtype=object)

In [5]:
fortune["Sector"].nunique()

21

In [6]:

in_retailing =  fortune["Sector"] == "Retailing"
retail_companies = fortune[ in_retailing ]

In [7]:
retail_companies

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000
11,12,Costco Wholesale,Retailing,General Merchandisers,254450.0,7370.0,333000
21,22,Meta Platforms,Retailing,Internet Services and Retailing,164500.0,62360.0,74070
23,24,Home Depot,Retailing,Specialty Retailers: Other,159510.0,14810.0,470100
...,...,...,...,...,...,...,...
912,913,Guess,Retailing,Specialty Retailers: Apparel,3000.0,60.4,13000
954,955,Etsy,Retailing,Internet Services and Retailing,2810.0,303.3,2400
977,978,Rackspace Technology,Retailing,Internet Services and Retailing,2740.0,-858.2,5100
978,979,CoStar Group,Retailing,Internet Services and Retailing,2740.0,138.7,6590
982,983,Caleres,Retailing,Specialty Retailers: Apparel,2720.0,107.3,7100

In [8]:

retail_companies["Revenues_M"].sum()

np.float64(3015650.0)

In [10]:
fortune

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees
0,1,Walmart,Retailing,General Merchandisers,680990.0,19440.0,2100000
1,2,Amazon,Retailing,Internet Services and Retailing,637960.0,59250.0,1560000
2,3,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,400280.0,14400.0,400000
3,4,Apple,Technology,"Computers, Office Equipment",391040.0,93740.0,164000
4,5,CVS Health,Health Care,Health Care: Pharmacy and Other Services,372810.0,4610.0,259500
...,...,...,...,...,...,...,...
995,996,Datadog,Technology,Computer Software,2680.0,183.7,6500
996,997,SBA Communications,Financials,Real estate,2680.0,749.5,1720
997,998,Quad/Graphics,Media,"Publishing, Printing",2670.0,-50.9,12200
998,999,Americold Realty Trust,Financials,Real estate,2670.0,-94.3,13760
999,1000,KinderCare Learning,Business Services,Education,2660.0,-92.8,43690

In [9]:
fortune.groupby("Sector")

In [11]:
sectors = fortune.groupby("Sector")

In [12]:
sectors

In [13]:
sectors.groups

{'Aerospace & Defense': [53, 58, 62, 95, 109, 117, 202, 310, 367, 474, 497, 530, 558, 602, 641, 736, 794, 829, 868, 897, 985], 'Apparel': [89, 404, 440, 448, 533, 536, 555, 597, 681, 742, 764, 862, 888, 950], 'Business Services': [126, 136, 151, 178, 196, 207, 219, 231, 238, 244, 265, 275, 284, 304, 396, 401, 412, 426, 457, 516, 540, 549, 566, 585, 591, 601, 637, 646, 659, 661, 673, 678, 686, 688, 732, 738, 751, 754, 755, 765, 778, 780, 816, 820, 858, 865, 867, 933, 940, 944, 946, 951, 955, 959, 965, 973, 980, 994, 999], 'Chemicals': [102, 173, 190, 233, 273, 338, 344, 346, 368, 380, 411, 430, 503, 545, 576, 583, 593, 623, 745, 776, 838, 840, 876, 962], 'Energy': [7, 15, 27, 28, 33, 52, 74, 77, 91, 105, 129, 134, 143, 149, 152, 154, 158, 160, 168, 172, 175, 182, 185, 191, 193, 199, 217, 224, 234, 240, 255, 263, 266, 274, 285, 288, 318, 321, 325, 326, 335, 336, 342, 352, 354, 382, 403, 408, 421, 437, 442, 449, 450, 453, 473, 492, 502, 504, 509, 523, 588, 614, 615, 622, 638, 640, 643, 652, 653, 662, 669, 683, 698, 735, 739, 749, 750, 752, 753, 760, 779, 805, 823, 824, 830, 844, 852, 885, 895, 907, 914, 920, 924, 931, 968, 991, 992], 'Engineering & Construction': [122, 128, 183, 228, 246, 256, 258, 299, 341, 389, 395, 466, 519, 520, 525, 553, 554, 631, 645, 695, 713, 714, 719, 724, 734, 774, 864, 910, 928, 939, 949], 'Financials': [5, 10, 16, 20, 24, 31, 32, 35, 37, 39, 41, 56, 57, 59, 61, 65, 68, 71, 81, 90, 92, 97, 98, 101, 104, 108, 112, 127, 130, 135, 144, 156, 161, 162, 163, 167, 174, 177, 184, 187, 195, 197, 201, 209, 221, 223, 227, 229, 236, 250, 252, 254, 259, 262, 268, 269, 271, 279, 292, 293, 298, 309, 312, 315, 316, 319, 320, 322, 329, 337, 339, 340, 350, 355, 360, 366, 370, 383, 387, 402, 405, 416, 431, 432, 435, 445, 452, 459, 462, 463, 464, 468, 471, 501, 506, 511, 514, 543, 544, 556, ...], 'Food & Drug Stores': [25, 26, 54, 70, 480, 603, 687, 728], 'Food, Beverages & Tobacco': [44, 49, 84, 96, 114, 120, 124, 165, 208, 215, 245, 261, 283, 331, 349, 351, 365, 377, 378, 417, 424, 438, 465, 476, 493, 498, 527, 532, 550, 596, 650, 655, 758, 866, 971, 984], 'Health Care': [2, 4, 8, 9, 12, 14, 19, 22, 38, 47, 60, 64, 66, 76, 93, 99, 106, 110, 133, 148, 179, 194, 205, 210, 218, 247, 270, 281, 287, 297, 305, 327, 330, 332, 334, 376, 384, 394, 418, 423, 434, 436, 458, 461, 482, 526, 542, 552, 565, 575, 578, 625, 663, 697, 721, 726, 744, 746, 768, 770, 771, 775, 787, 788, 804, 873, 877, 892, 894, 898, 904, 915, 936, 941, 947, 956, 960, 961, 963, 967, 970, 972, 986], 'Hotels, Restaurants & Leisure': [125, 164, 170, 239, 369, 371, 372, 373, 375, 379, 490, 512, 535, 541, 624, 666, 671, 689, 694, 716, 723, 785, 793, 837, 851, 886, 938, 979], 'Household Products': [50, 211, 212, 278, 280, 282, 390, 477, 486, 515, 571, 573, 621, 676, 725, 762, 826, 884, 891, 922, 937, 988], 'Industrials': [63, 88, 118, 131, 171, 214, 237, 251, 267, 302, 323, 363, 392, 407, 451, 455, 460, 470, 508, 562, 577, 605, 628, 651, 654, 667, 705, 707, 709, 740, 741, 761, 773, 790, 797, 800, 810, 825, 832, 836, 871, 883, 887, 917, 974, 993], 'Materials': [139, 220, 225, 235, 253, 277, 308, 343, 348, 353, 358, 386, 443, 444, 456, 475, 499, 510, 513, 529, 534, 537, 546, 547, 587, 616, 620, 630, 635, 703, 704, 729, 767, 806, 808, 815, 834, 854, 908, 929, 935, 943, 966, 975, 990], 'Media': [45, 113, 115, 146, 189, 307, 413, 447, 489, 494, 551, 619, 627, 658, 702, 747, 763, 795, 819, 822, 831, 841, 899, 903, 983, 997], 'Motor Vehicles & Parts': [17, 18, 42, 132, 188, 222, 306, 406, 409, 414, 570, 670, 792, 813, 850, 857, 879, 919, 981], 'Retailing': [0, 1, 11, 21, 23, 40, 51, 75, 107, 111, 123, 138, 140, 141, 150, 159, 192, 203, 206, 213, 226, 230, 241, 248, 260, 289, 290, 295, 296, 303, 311, 313, 317, 356, 357, 359, 374, 381, 388, 393, 398, 400, 410, 415, 439, 472, 478, 481, 487, 505, 522, 539, 563, 572, 574, 584, 604, 609, 626, 632, 649, 675, 679, 717, 718, 737, 748, 789, 798, 802, 814, 821, 827, 839, 848, 859, 861, 889, 906, 909, 912, 954, 977, 978, 982], 'Technology': [3, 6, 13, 30, 43, 67, 82, 83, 85, 86, 87, 100, 103, 116, 119, 142, 147, 157, 166, 169, 181, 200, 204, 216, 249, 257, 264, 276, 286, 291, 294, 314, 328, 385, 391, 397, 419, 425, 429, 446, 454, 469, 479, 483, 484, 488, 495, 517, 518, 521, 524, 528, 538, 548, 557, 559, 560, 564, 567, 580, 586, 592, 595, 610, 634, 657, 668, 690, 692, 693, 699, 700, 706, 727, 730, 743, 759, 772, 777, 782, 783, 791, 801, 809, 812, 817, 833, 863, 869, 875, 890, 918, 923, 930, 945, 952, 953, 969, 995], 'Telecommunications': [29, 34, 36, 78, 272, 324, 441, 582, 672], 'Transportation': [46, 48, 69, 73, 80, 155, 176, 232, 300, 333, 345, 347, 361, 362, 399, 433, 467, 500, 507, 590, 606, 636, 642, 648, 680, 684, 710, 757, 784, 807, 842, 843, 855, 872, 881, 900, 905], 'Wholesalers': [55, 72, 79, 94, 121, 137, 145, 153, 180, 186, 198, 242, 243, 301, 364, 420, 422, 427, 428, 485, 491, 496, 531, 611, 633, 711, 715, 799, 803, 874, 926, 957, 987]}

In [14]:
len(sectors)

21

In [15]:
fortune.describe()

              Rank     Revenues_M      Profits_M  Number_of_Employees
count  1000.000000    1000.000000     999.000000         1.000000e+03
mean    500.496000   22126.030000    2029.904805         3.657326e+04
std     288.817395   52097.453341    7662.758649         9.989464e+04
min       1.000000    2660.000000  -18760.000000         2.700000e+01
25%     250.750000    4240.000000     178.600000         7.000000e+03
50%     500.500000    7415.000000     566.800000         1.460000e+04
75%     750.250000   16630.000000    1570.000000         3.186500e+04
max    1000.000000  680990.000000  100120.000000         2.100000e+06

In [16]:
sectors.describe()

                                Rank                                         \
                               count        mean         std    min     25%
Sector
Aerospace & Defense             21.0  466.904762  314.853760   54.0  118.00
Apparel                         14.0  607.357143  229.716081   90.0  470.25
Business Services               59.0  615.237288  274.311825  127.0  399.50
Chemicals                       24.0  503.000000  243.385363  103.0  343.50
Energy                          97.0  457.237113  286.541474    8.0  194.00
Engineering & Construction      31.0  546.838710  254.555966  123.0  321.00
Financials                     178.0  477.814607  296.832477    6.0  222.50
Food & Drug Stores               8.0  335.125000  318.918457   26.0   48.00
Food, Beverages & Tobacco       36.0  402.611111  247.190878   45.0  214.25
Health Care                     83.0  482.289157  334.001881    3.0  187.50
Hotels, Restaurants & Leisure   28.0  567.678571  245.086841  126.0  373.75
Household Products              22.0  571.772727  276.551542   51.0  310.00
Industrials                     46.0  574.152174  264.564629   64.0  371.25
Materials                       45.0  583.933333  239.917448  140.0  387.00
Media                           26.0  590.038462  291.051402   46.0  422.50
Motor Vehicles & Parts          19.0  500.210526  338.715807   18.0  206.00
Retailing                       85.0  463.705882  286.571599    1.0  231.00
Technology                      99.0  496.232323  284.192979    4.0  254.00
Telecommunications               9.0  275.222222  249.084713   30.0   37.00
Transportation                  37.0  511.135135  279.675820   47.0  334.00
Wholesalers                     33.0  433.909091  289.024044   56.0  181.00

                                                     Revenues_M                \
                                 50%     75%     max      count          mean
Sector
Aerospace & Defense            498.0  737.00   986.0       21.0  21551.904762
Apparel                        577.0  759.50   951.0       14.0   9105.714286
Business Services              662.0  840.00  1000.0       59.0   8686.949153
Chemicals                      467.5  654.50   963.0       24.0  10891.250000
Energy                         422.0  699.00   993.0       97.0  23085.463918
Engineering & Construction     554.0  722.50   950.0       31.0  10001.935484
Financials                     463.5  719.00   999.0      178.0  23670.449438
Food & Drug Stores             276.0  625.00   729.0        8.0  57090.000000
Food, Beverages & Tobacco      378.5  529.25   985.0       36.0  19042.500000
Health Care                    437.0  782.00   987.0       83.0  40791.927711
Hotels, Restaurants & Leisure  583.5  739.50   980.0       28.0   9194.285714
Household Products             573.0  811.00   989.0       22.0  11526.363636
Industrials                    640.5  796.25   994.0       46.0  10818.043478
Materials                      547.0  807.00   991.0       45.0   8061.333333
Media                          643.5  822.25   998.0       26.0  12881.538462
Motor Vehicles & Parts         415.0  832.50   982.0       19.0  32909.473684
Retailing                      411.0  718.00   983.0       85.0  35478.235294
Technology                     522.0  729.50   996.0       99.0  24561.515152
Telecommunications             273.0  442.00   673.0        9.0  53860.000000
Transportation                 508.0  758.00   906.0       37.0  16622.162162
Wholesalers                    423.0  634.00   988.0       33.0  18265.454545

                               ...  Profits_M           Number_of_Employees  \
                               ...        75%       max               count
Sector                         ...
Aerospace & Defense            ...   1710.000    6560.0                21.0
Apparel                        ...    731.275    5700.0                14.0
Business Services              ...   1465.000   19740.0                59.0
Chemicals                      ...   1120.000    4170.0                24.0
Energy                         ...   2500.000   33680.0                97.0
Engineering & Construction     ...    957.400    4760.0                31.0
Financials                     ...   2555.000   89000.0               178.0
Food & Drug Stores             ...   1642.500    4630.0                 8.0
Food, Beverages & Tobacco      ...   1747.500   11260.0                36.0
Health Care                    ...   2155.000   17120.0                83.0
Hotels, Restaurants & Leisure  ...   1337.500    8220.0                28.0
Household Products             ...    574.425   14880.0                22.0
Industrials                    ...   1018.125   10790.0                46.0
Materials                      ...    647.000    4010.0                45.0
Media                          ...    558.600    8710.0                26.0
Motor Vehicles & Parts         ...    688.500    7090.0                19.0
Retailing                      ...   1100.000   62360.0                85.0
Technology                     ...   2340.000  100120.0                99.0
Telecommunications             ...  10950.000   17510.0                 9.0
Transportation                 ...    819.075    6750.0                37.0
Wholesalers                    ...    536.300    1960.0                33.0

                                                                              \
                                        mean            std     min      25%
Sector
Aerospace & Defense             49547.619048   55310.208904  7700.0  13500.0
Apparel                         20442.857143   19245.402819  4050.0  10060.0
Business Services               29941.779661   38160.022238   165.0  10900.0
Chemicals                       19282.916667   18359.867263  2060.0   6275.0
Energy                          10480.711340   13425.075642   452.0   2080.0
Engineering & Construction      15301.612903   15137.268379  1690.0   3175.0
Financials                      22250.955056   49089.608650    27.0   3640.0
Food & Drug Stores             148858.750000  150961.438448  2000.0  21180.0
Food, Beverages & Tobacco       32835.833333   56607.568619  2260.0   9975.0
Health Care                     42671.566265   60962.150582  1080.0  10375.0
Hotels, Restaurants & Leisure   79148.571429   84608.947023  5100.0  22175.0
Household Products              23695.454545   24307.160365  2890.0   6710.0
Industrials                     27508.913043   25632.543311  5170.0  10877.5
Materials                       15683.111111    9648.329300  3010.0   9400.0
Media                           22155.000000   38938.205942  1180.0   7672.5
Motor Vehicles & Parts          52723.684211   59254.087174  4000.0  12100.0
Retailing                       92020.235294  288400.904818  1470.0  11750.0
Technology                      45229.090909   71002.839007  1550.0  11010.0
Telecommunications              65291.111111   65812.155307  7900.0  13030.0
Transportation                  50948.378378   90707.414144  1440.0  12900.0
Wholesalers                     17950.181818   17791.372729   486.0   6100.0


                                    50%       75%        max
Sector
Aerospace & Defense             20370.0   53000.0   186000.0
Apparel                         15450.0   21275.0    79400.0
Business Services               19350.0   40000.0   266680.0
Chemicals                       12965.0   22822.5    63890.0
Energy                           6650.0   13050.0    76800.0
Engineering & Construction       9450.0   22585.0    58400.0
Financials                       7485.0   18905.0   392400.0
Food & Drug Stores             115825.0  253125.0   409000.0
Food, Beverages & Tobacco       14950.0   25350.0   319000.0
Health Care                     22050.0   53000.0   400000.0
Hotels, Restaurants & Leisure   48950.0  103875.0   361000.0
Household Products              14850.0   34000.0   108000.0
Industrials                     16850.0   30887.5   112900.0
Materials                       13900.0   21000.0    42000.0
Media                           12380.0   20070.0   205040.0
Motor Vehicles & Parts          23250.0   65135.0   173700.0
Retailing                       20160.0   39000.0  2100000.0
Technology                      21000.0   37500.0   450000.0
Telecommunications              25000.0   99600.0   182000.0
Transportation                  19400.0   35300.0   422100.0
Wholesalers                     10000.0   25750.0    76000.0

[21 rows x 32 columns]

In [17]:
sectors['Revenues_M'].describe()

,count,mean,std,min,25%,50%,75%,max
Sector,,,,,,,,
Aerospace & Defense,21.0,21551.904762,25306.241447,2700.0,4320.0,7430.0,38700.0,80740.0
Apparel,14.0,9105.714286,12377.962871,2840.0,4147.5,6030.0,8155.0,51360.0
Business Services,59.0,8686.949153,7885.896677,2660.0,3520.0,5010.0,10615.0,35930.0
Chemicals,24.0,10891.250000,9094.969614,2790.0,5097.5,8360.0,12202.5,42960.0
Energy,97.0,23085.463918,45986.944728,2690.0,4680.0,9740.0,22940.0,349580.0
Engineering & Construction,31.0,10001.935484,8820.845545,2850.0,4425.0,6390.0,13435.0,36800.0
Financials,178.0,23670.449438,45294.021953,2670.0,4470.0,8230.0,18892.5,371430.0
Food & Drug Stores,8.0,57090.000000,62573.024996,4370.0,5427.5,33950.0,96210.0,147660.0
"Food, Beverages & Tobacco",36.0,19042.500000,21340.629710,2710.0,6855.0,11230.0,20005.0,91850.0
Health Care,83.0,40791.927711,83165.727029,2700.0,3950.0,9180.0,23235.0,400280.0
"Hotels, Restaurants & Leisure",28.0,9194.285714,8039.998815,2730.0,4297.5,5975.0,11300.0,36180.0
Household Products,22.0,11526.363636,17146.296989,2700.0,3757.5,6115.0,14237.5,84040.0
Industrials,46.0,10818.043478,12949.209434,2690.0,3850.0,5235.0,11427.5,64810.0
Materials,45.0,8061.333333,5757.547458,2700.0,3780.0,6540.0,10970.0,30730.0
Media,26.0,12881.538462,19242.307906,2670.0,3642.5,5205.0,9742.5,91360.0
Motor Vehicles & Parts,19.0,32909.473684,58217.989438,2730.0,3610.0,10040.0,21095.0,187440.0
Retailing,85.0,35478.235294,104592.590232,2720.0,4460.0,10280.0,17910.0,680990.0
Technology,99.0,24561.515152,58625.816532,2680.0,4365.0,7000.0,16475.0,391040.0
Telecommunications,9.0,53860.000000,56936.140763,4960.0,8950.0,15830.0,122340.0,134790.0
Transportation,37.0,16622.162162,23010.793498,3030.0,4180.0,7270.0,12640.0,91070.0
Wholesalers,33.0,18265.454545,18741.270316,2700.0,5310.0,9700.0,23760.0,78840.0

In [18]:
fortune.groupby("Sector")["Revenues_M"].mean() # Series

Sector
Aerospace & Defense              21551.904762
Apparel                           9105.714286
Business Services                 8686.949153
Chemicals                        10891.250000
Energy                           23085.463918
Engineering & Construction       10001.935484
Financials                       23670.449438
Food & Drug Stores               57090.000000
Food, Beverages & Tobacco        19042.500000
Health Care                      40791.927711
Hotels, Restaurants & Leisure     9194.285714
Household Products               11526.363636
Industrials                      10818.043478
Materials                         8061.333333
Media                            12881.538462
Motor Vehicles & Parts           32909.473684
Retailing                        35478.235294
Technology                       24561.515152
Telecommunications               53860.000000
Transportation                   16622.162162
Wholesalers                      18265.454545
Name: Revenues_M, dtype: float64

In [19]:

fortune.groupby("Sector")["Revenues_M"].median()

Sector
Aerospace & Defense               7430.0
Apparel                           6030.0
Business Services                 5010.0
Chemicals                         8360.0
Energy                            9740.0
Engineering & Construction        6390.0
Financials                        8230.0
Food & Drug Stores               33950.0
Food, Beverages & Tobacco        11230.0
Health Care                       9180.0
Hotels, Restaurants & Leisure     5975.0
Household Products                6115.0
Industrials                       5235.0
Materials                         6540.0
Media                             5205.0
Motor Vehicles & Parts           10040.0
Retailing                        10280.0
Technology                        7000.0
Telecommunications               15830.0
Transportation                    7270.0
Wholesalers                       9700.0
Name: Revenues_M, dtype: float64

In [20]:

fortune.groupby("Sector")["Revenues_M"].max()

Sector
Aerospace & Defense               80740.0
Apparel                           51360.0
Business Services                 35930.0
Chemicals                         42960.0
Energy                           349580.0
Engineering & Construction        36800.0
Financials                       371430.0
Food & Drug Stores               147660.0
Food, Beverages & Tobacco         91850.0
Health Care                      400280.0
Hotels, Restaurants & Leisure     36180.0
Household Products                84040.0
Industrials                       64810.0
Materials                         30730.0
Media                             91360.0
Motor Vehicles & Parts           187440.0
Retailing                        680990.0
Technology                       391040.0
Telecommunications               134790.0
Transportation                    91070.0
Wholesalers                       78840.0
Name: Revenues_M, dtype: float64

In [21]:

fortune.groupby("Sector")["Revenues_M"].min()

Sector
Aerospace & Defense              2700.0
Apparel                          2840.0
Business Services                2660.0
Chemicals                        2790.0
Energy                           2690.0
Engineering & Construction       2850.0
Financials                       2670.0
Food & Drug Stores               4370.0
Food, Beverages & Tobacco        2710.0
Health Care                      2700.0
Hotels, Restaurants & Leisure    2730.0
Household Products               2700.0
Industrials                      2690.0
Materials                        2700.0
Media                            2670.0
Motor Vehicles & Parts           2730.0
Retailing                        2720.0
Technology                       2680.0
Telecommunications               4960.0
Transportation                   3030.0
Wholesalers                      2700.0
Name: Revenues_M, dtype: float64

In [23]:

sectors_revenues = fortune.groupby("Sector")["Revenues_M"].sum()

In [26]:
fortune.groupby("Sector")["Revenues_M"]

In [25]:
type(fortune.groupby("Sector")["Revenues_M"])

pandas.core.groupby.generic.SeriesGroupBy

In [27]:
fortune.groupby("Sector").size() # number of observations in each group

Sector
Aerospace & Defense               21
Apparel                           14
Business Services                 59
Chemicals                         24
Energy                            97
Engineering & Construction        31
Financials                       178
Food & Drug Stores                 8
Food, Beverages & Tobacco         36
Health Care                       83
Hotels, Restaurants & Leisure     28
Household Products                22
Industrials                       46
Materials                         45
Media                             26
Motor Vehicles & Parts            19
Retailing                         85
Technology                        99
Telecommunications                 9
Transportation                    37
Wholesalers                       33
dtype: int64

In [29]:
(
  fortune.groupby("Sector")[["Revenues_M","Profits_M","Number_of_Employees"]]
  .mean()
)

                                 Revenues_M    Profits_M  Number_of_Employees
Sector
Aerospace & Defense            21551.904762   918.342857         49547.619048
Apparel                         9105.714286   704.692857         20442.857143
Business Services               8686.949153  1386.984746         29941.779661
Chemicals                      10891.250000   759.179167         19282.916667
Energy                         23085.463918  2027.406186         10480.711340
Engineering & Construction     10001.935484   902.319355         15301.612903
Financials                     23670.449438  2856.694944         22250.955056
Food & Drug Stores             57090.000000    74.437500        148858.750000
Food, Beverages & Tobacco      19042.500000  1948.900000         32835.833333
Health Care                    40791.927711  1728.380723         42671.566265
Hotels, Restaurants & Leisure   9194.285714   972.925000         79148.571429
Household Products             11526.363636  1126.604545         23695.454545
Industrials                    10818.043478  1354.413043         27508.913043
Materials                       8061.333333   489.253333         15683.111111
Media                          12881.538462  -392.876923         22155.000000
Motor Vehicles & Parts         32909.473684  1138.794737         52723.684211
Retailing                      35478.235294  2412.820000         92020.235294
Technology                     24561.515152  5002.012121         45229.090909
Telecommunications             53860.000000  5455.844444         65291.111111
Transportation                 16622.162162  1059.086111         50948.378378
Wholesalers                    18265.454545   486.381818         17950.181818

In [30]:
fortune.groupby("Sector")["Revenues_M"]  # this is a SeriesGroupBy object

In [31]:
fortune.groupby("Sector")["Revenues_M"].agg('sum')

Sector
Aerospace & Defense               452590.0
Apparel                           127480.0
Business Services                 512530.0
Chemicals                         261390.0
Energy                           2239290.0
Engineering & Construction        310060.0
Financials                       4213340.0
Food & Drug Stores                456720.0
Food, Beverages & Tobacco         685530.0
Health Care                      3385730.0
Hotels, Restaurants & Leisure     257440.0
Household Products                253580.0
Industrials                       497630.0
Materials                         362760.0
Media                             334920.0
Motor Vehicles & Parts            625280.0
Retailing                        3015650.0
Technology                       2431590.0
Telecommunications                484740.0
Transportation                    615020.0
Wholesalers                       602760.0
Name: Revenues_M, dtype: float64

In [32]:
fortune.groupby("Sector")["Revenues_M"].sum()

Sector
Aerospace & Defense               452590.0
Apparel                           127480.0
Business Services                 512530.0
Chemicals                         261390.0
Energy                           2239290.0
Engineering & Construction        310060.0
Financials                       4213340.0
Food & Drug Stores                456720.0
Food, Beverages & Tobacco         685530.0
Health Care                      3385730.0
Hotels, Restaurants & Leisure     257440.0
Household Products                253580.0
Industrials                       497630.0
Materials                         362760.0
Media                             334920.0
Motor Vehicles & Parts            625280.0
Retailing                        3015650.0
Technology                       2431590.0
Telecommunications                484740.0
Transportation                    615020.0
Wholesalers                       602760.0
Name: Revenues_M, dtype: float64

In [33]:

fortune.groupby("Sector")["Revenues_M"].agg('mean')

Sector
Aerospace & Defense              21551.904762
Apparel                           9105.714286
Business Services                 8686.949153
Chemicals                        10891.250000
Energy                           23085.463918
Engineering & Construction       10001.935484
Financials                       23670.449438
Food & Drug Stores               57090.000000
Food, Beverages & Tobacco        19042.500000
Health Care                      40791.927711
Hotels, Restaurants & Leisure     9194.285714
Household Products               11526.363636
Industrials                      10818.043478
Materials                         8061.333333
Media                            12881.538462
Motor Vehicles & Parts           32909.473684
Retailing                        35478.235294
Technology                       24561.515152
Telecommunications               53860.000000
Transportation                   16622.162162
Wholesalers                      18265.454545
Name: Revenues_M, dtype: float64

In [34]:
fortune.groupby("Sector")["Revenues_M"].mean()

Sector
Aerospace & Defense              21551.904762
Apparel                           9105.714286
Business Services                 8686.949153
Chemicals                        10891.250000
Energy                           23085.463918
Engineering & Construction       10001.935484
Financials                       23670.449438
Food & Drug Stores               57090.000000
Food, Beverages & Tobacco        19042.500000
Health Care                      40791.927711
Hotels, Restaurants & Leisure     9194.285714
Household Products               11526.363636
Industrials                      10818.043478
Materials                         8061.333333
Media                            12881.538462
Motor Vehicles & Parts           32909.473684
Retailing                        35478.235294
Technology                       24561.515152
Telecommunications               53860.000000
Transportation                   16622.162162
Wholesalers                      18265.454545
Name: Revenues_M, dtype: float64

In [35]:

fortune.groupby("Sector")["Revenues_M"].agg('max')

Sector
Aerospace & Defense               80740.0
Apparel                           51360.0
Business Services                 35930.0
Chemicals                         42960.0
Energy                           349580.0
Engineering & Construction        36800.0
Financials                       371430.0
Food & Drug Stores               147660.0
Food, Beverages & Tobacco         91850.0
Health Care                      400280.0
Hotels, Restaurants & Leisure     36180.0
Household Products                84040.0
Industrials                       64810.0
Materials                         30730.0
Media                             91360.0
Motor Vehicles & Parts           187440.0
Retailing                        680990.0
Technology                       391040.0
Telecommunications               134790.0
Transportation                    91070.0
Wholesalers                       78840.0
Name: Revenues_M, dtype: float64

In [36]:

fortune.groupby("Sector")["Revenues_M"].agg('min')

Sector
Aerospace & Defense              2700.0
Apparel                          2840.0
Business Services                2660.0
Chemicals                        2790.0
Energy                           2690.0
Engineering & Construction       2850.0
Financials                       2670.0
Food & Drug Stores               4370.0
Food, Beverages & Tobacco        2710.0
Health Care                      2700.0
Hotels, Restaurants & Leisure    2730.0
Household Products               2700.0
Industrials                      2690.0
Materials                        2700.0
Media                            2670.0
Motor Vehicles & Parts           2730.0
Retailing                        2720.0
Technology                       2680.0
Telecommunications               4960.0
Transportation                   3030.0
Wholesalers                      2700.0
Name: Revenues_M, dtype: float64

In [37]:
fortune.groupby("Sector").agg(
  Revenues_M_min = ("Revenues_M", "min"),
  Profits_M_max = ("Profits_M", "max"),
  Number_of_Employees_mean = ("Number_of_Employees", "mean")
)

,Revenues_M_min,Profits_M_max,Number_of_Employees_mean
Sector,,,
Aerospace & Defense,2700.0,6560.0,49547.619048
Apparel,2840.0,5700.0,20442.857143
Business Services,2660.0,19740.0,29941.779661
Chemicals,2790.0,4170.0,19282.916667
Energy,2690.0,33680.0,10480.711340
Engineering & Construction,2850.0,4760.0,15301.612903
Financials,2670.0,89000.0,22250.955056
Food & Drug Stores,4370.0,4630.0,148858.750000
"Food, Beverages & Tobacco",2710.0,11260.0,32835.833333
Health Care,2700.0,17120.0,42671.566265
"Hotels, Restaurants & Leisure",2730.0,8220.0,79148.571429
Household Products,2700.0,14880.0,23695.454545
Industrials,2690.0,10790.0,27508.913043
Materials,2700.0,4010.0,15683.111111
Media,2670.0,8710.0,22155.000000
Motor Vehicles & Parts,2730.0,7090.0,52723.684211
Retailing,2720.0,62360.0,92020.235294
Technology,2680.0,100120.0,45229.090909
Telecommunications,4960.0,17510.0,65291.111111
Transportation,3030.0,6750.0,50948.378378
Wholesalers,2700.0,1960.0,17950.181818

In [38]:
fortune.columns

Index(['Rank', 'Company', 'Sector', 'Industry', 'Revenues_M', 'Profits_M',
       'Number_of_Employees'],
      dtype='object')

In [40]:
fortune.groupby("Sector").agg(
  n_companies = ("Company", "size"),
  Revenues_M_min = ("Revenues_M", "min"),
  Profits_M_max = ("Profits_M", "max"),
  Number_of_Employees_mean = ("Number_of_Employees", "mean")
)

,n_companies,Revenues_M_min,Profits_M_max,Number_of_Employees_mean
Sector,,,,
Aerospace & Defense,21,2700.0,6560.0,49547.619048
Apparel,14,2840.0,5700.0,20442.857143
Business Services,59,2660.0,19740.0,29941.779661
Chemicals,24,2790.0,4170.0,19282.916667
Energy,97,2690.0,33680.0,10480.711340
Engineering & Construction,31,2850.0,4760.0,15301.612903
Financials,178,2670.0,89000.0,22250.955056
Food & Drug Stores,8,4370.0,4630.0,148858.750000
"Food, Beverages & Tobacco",36,2710.0,11260.0,32835.833333
Health Care,83,2700.0,17120.0,42671.566265
"Hotels, Restaurants & Leisure",28,2730.0,8220.0,79148.571429
Household Products,22,2700.0,14880.0,23695.454545
Industrials,46,2690.0,10790.0,27508.913043
Materials,45,2700.0,4010.0,15683.111111
Media,26,2670.0,8710.0,22155.000000
Motor Vehicles & Parts,19,2730.0,7090.0,52723.684211
Retailing,85,2720.0,62360.0,92020.235294
Technology,99,2680.0,100120.0,45229.090909
Telecommunications,9,4960.0,17510.0,65291.111111
Transportation,37,3030.0,6750.0,50948.378378
Wholesalers,33,2700.0,1960.0,17950.181818

In [41]:
fortune.groupby("Sector").agg(
  n_companies = ("Profits_M", "size"),
  Revenues_M_min = ("Revenues_M", "min"),
  Profits_M_max = ("Profits_M", "max"),
  Number_of_Employees_mean = ("Number_of_Employees", "mean")
)

,n_companies,Revenues_M_min,Profits_M_max,Number_of_Employees_mean
Sector,,,,
Aerospace & Defense,21,2700.0,6560.0,49547.619048
Apparel,14,2840.0,5700.0,20442.857143
Business Services,59,2660.0,19740.0,29941.779661
Chemicals,24,2790.0,4170.0,19282.916667
Energy,97,2690.0,33680.0,10480.711340
Engineering & Construction,31,2850.0,4760.0,15301.612903
Financials,178,2670.0,89000.0,22250.955056
Food & Drug Stores,8,4370.0,4630.0,148858.750000
"Food, Beverages & Tobacco",36,2710.0,11260.0,32835.833333
Health Care,83,2700.0,17120.0,42671.566265
"Hotels, Restaurants & Leisure",28,2730.0,8220.0,79148.571429
Household Products,22,2700.0,14880.0,23695.454545
Industrials,46,2690.0,10790.0,27508.913043
Materials,45,2700.0,4010.0,15683.111111
Media,26,2670.0,8710.0,22155.000000
Motor Vehicles & Parts,19,2730.0,7090.0,52723.684211
Retailing,85,2720.0,62360.0,92020.235294
Technology,99,2680.0,100120.0,45229.090909
Telecommunications,9,4960.0,17510.0,65291.111111
Transportation,37,3030.0,6750.0,50948.378378
Wholesalers,33,2700.0,1960.0,17950.181818

In [44]:
(
    fortune
    .groupby('Sector')
    .agg(
        Revenue_IQR = ('Revenues_M', lambda s: s.quantile(.75) - s.quantile(.25) ),
        Profit_IQR = ('Profits_M', lambda s: s.quantile(.75) - s.quantile(.25) ),
        Number_of_Employees_IQR = ('Number_of_Employees', lambda s: s.quantile(.75) - s.quantile(.25) )
    )
)

,Revenue_IQR,Profit_IQR,Number_of_Employees_IQR
Sector,,,
Aerospace & Defense,34380.0,1474.900,39500.0
Apparel,4007.5,533.425,11215.0
Business Services,7095.0,1298.950,29100.0
Chemicals,7105.0,995.125,16547.5
Energy,18260.0,2179.700,10970.0
Engineering & Construction,9010.0,719.700,19410.0
Financials,14422.5,2109.925,15265.0
Food & Drug Stores,90782.5,1553.500,231945.0
"Food, Beverages & Tobacco",13150.0,1417.375,15375.0
Health Care,19285.0,2131.200,42625.0
"Hotels, Restaurants & Leisure",7002.5,1181.075,81700.0
Household Products,10480.0,490.350,27290.0
Industrials,7577.5,650.100,20010.0
Materials,7190.0,508.600,11600.0
Media,6100.0,1549.950,12397.5
Motor Vehicles & Parts,17485.0,636.000,53035.0
Retailing,13450.0,1027.600,27250.0
Technology,12110.0,2089.550,26490.0
Telecommunications,113390.0,11052.900,86570.0
Transportation,8460.0,686.050,22400.0
Wholesalers,18450.0,426.000,19650.0

In [45]:
(
    fortune
    .groupby('Sector')
    .agg(
        Revenue_Q1 = ('Revenues_M', 'quantile(.25)')
    )
)

AttributeError: 'SeriesGroupBy' object has no attribute 'quantile(.25)'

In [46]:
def IQR(s):
  return s.quantile(.75) - s.quantile(.25)

In [48]:
(
    fortune
    .groupby('Sector')
    .agg(
        Revenue_IQR = ('Revenues_M', IQR)
    )
)

                               Revenue_IQR
Sector
Aerospace & Defense                34380.0
Apparel                             4007.5
Business Services                   7095.0
Chemicals                           7105.0
Energy                             18260.0
Engineering & Construction          9010.0
Financials                         14422.5
Food & Drug Stores                 90782.5
Food, Beverages & Tobacco          13150.0
Health Care                        19285.0
Hotels, Restaurants & Leisure       7002.5
Household Products                 10480.0
Industrials                         7577.5
Materials                           7190.0
Media                               6100.0
Motor Vehicles & Parts             17485.0
Retailing                          13450.0
Technology                         12110.0
Telecommunications                113390.0
Transportation                      8460.0
Wholesalers                        18450.0

In [49]:
fortune['Sector_rev_mean'] = (
    fortune.groupby('Sector')['Revenues_M'].transform('mean')
)

/tmp/ipykernel_11761/3593059741.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fortune['Sector_rev_mean'] = (

In [51]:
fortune.sort_values('Sector')

,Rank,Company,Sector,Industry,Revenues_M,Profits_M,Number_of_Employees,Sector_rev_mean
558,559,Spirit AeroSystems Holdings,Aerospace & Defense,Aerospace & Defense,6320.0,-2140.0,20370,21551.904762
310,311,Textron,Aerospace & Defense,Aerospace & Defense,13700.0,824.0,34000,21551.904762
985,986,BWX Technologies,Aerospace & Defense,Aerospace & Defense,2700.0,281.9,8700,21551.904762
829,830,Moog,Aerospace & Defense,Aerospace & Defense,3610.0,207.2,13500,21551.904762
117,118,General Electric (GE Aerospace),Aerospace & Defense,Aerospace & Defense,38700.0,6560.0,53000,21551.904762
...,...,...,...,...,...,...,...,...
180,181,Avnet,Wholesalers,Wholesalers: Electronics and Office Equipment,23760.0,498.7,15460,18265.454545
186,187,Genuine Parts,Wholesalers,Wholesalers: Diversified,23490.0,904.1,63000,18265.454545
301,302,LKQ,Wholesalers,Wholesalers: Diversified,14360.0,690.0,47000,18265.454545
711,712,SiteOne Landscape Supply,Wholesalers,Wholesalers: Diversified,4540.0,123.6,8070,18265.454545
121,122,US Foods Holding,Wholesalers,Wholesalers: Food and Grocery,37880.0,494.0,30000,18265.454545